(function(){function d(){}function k(a,b){return 0==ca.call(a).indexOf("[object "+b)}function l(a){return a&&"/"==a.charAt(a.length-1)?a.substr(0,a.length-1):a}function g(a,b){var c,d,e,f;c=1;d=a;"."==d.charAt(0)&&(e=w,d=d.replace(da,function(a,b,d,e){d&&c++;return e||""}));if(e){e=b.split("/");f=e.length-c;if(0>f)return a;e.splice(f,c);return e.concat(d||[]).join("/")}return d}function e(a){var b=a.indexOf("!");return{l:a.substr(b+1),j:0<=b&&a.substr(0,b)}}function c(){}function b(a,b){c.prototype=
a||S;var d=new c;c.prototype=S;for(var e in b)d[e]=b[e];return d}function a(){function a(b,c,d){e.push([b,c,d])}function b(a,c){for(var d,f=0;d=e[f++];)(d=d[a])&&d(c)}var c,e,f;c=this;e=[];f=function(c,h){a=c?function(a){a&&a(h)}:function(a,b){b&&b(h)};f=d;b(c?0:1,h);b=d;e=C};this.z=function(b,c,d){a(b,c,d)};this.g=function(a){c.w=a;f(w,a)};this.d=function(a){c.oa=a;f(A,a)};this.t=function(a){b(2,a)}}function j(b,c,d,e){b instanceof a?b.z(c,d,e):c(b)}function m(a,b,c){var d;return function(){0<=--a&&
b&&(d=b.apply(C,arguments));0==a&&c&&c(d);return d}}function n(){var a=[].slice.call(arguments),b;k(a[0],"Object")&&(b=a.shift(),f(b));return new h(a[0],a[1],a[2])}function f(a){a&&(u.P(a),x=u.b(a),u.S(a),"main"in a&&setTimeout(function(){var b;b=u.f(x,C,[].concat(a.main));u.h(b)},0))}function h(a,b,c,d){var e;e=u.f(x,C,[].concat(a));this.then=a=function(a,b){j(e,function(b){a&&a.apply(C,b)},function(a){if(b)b(a);else throw a;});return this};this.next=function(a,b,c){return new h(a,b,c,e)};this.config=
f;(b||c)&&a(b,c);j(d,function(){u.h(e)})}function p(b){var c,d;c=b.id;if(c==C)if(M!==C)M={F:"Multiple anonymous defines in url"};else if(!(c=u.ba()))M=b;if(c!=C){d=F[c];c in F||(d=u.k(c,x),d=u.B(d.b,c),F[c]=d);if(!(d instanceof a))throw Error("duplicate define: "+c);d.ga=A;u.C(d,b)}}function q(){var a=u.Z(arguments);p(a)}function t(a){try{return eval(a)}catch(b){}}function s(){var a;a=I[ea]("link");a.rel="stylesheet";a.type="text/css";return a}function r(a,b,c){U.push({url:a,R:b,U:function(){c(Error(V))}});
a=W.shift();!a&&X.length<fa&&(a=I.createElement("style"),X.push(a),O.appendChild(a));a&&v(a)}function v(a){var b,c;b=U.shift();c=a.styleSheet;b?(a.onload=function(){b.R(b.ea);v(a)},a.onerror=function(){b.U();v(a)},b.ea=c.imports[c.addImport(b.url)]):(a.onload=a.onerror=y,W.push(a))}function D(a,b,c){if(!N.load){var d,e,f;if(!a.href||I.readyState&&"complete"!=I.readyState)d=A;else{d=A;try{if(e=a.sheet)f=e.cssRules,d=null===f,!d&&f&&(e.insertRule("-curl-css-test {}",0),e.deleteRule(0),d=w)}catch(h){d=
"[object Opera]"!=Object.prototype.toString.call(window.opera)&&/security|denied/i.test(h.message)}}d?c(a.sheet):a.onload==y||!a.onload||Y(function(){D(a,b,c)},b)}}function G(a,b,c,d){function e(){if(f.onload!=y&&f.onload){f.onload=f.onerror=y;var a=function(){!I.readyState||"complete"==I.readyState?b(f.sheet):Y(a,10)};a()}}var f;f=s();f.onload=function(){N.load=N.load||w;e()};D(f,d,e);f.onerror=function(){N.error=N.error||w;f.onload!=y&&f.onload&&(f.onload=f.onerror=y,c(Error(V)))};f.href=a;O.appendChild(f)}
function y(){}var w=!0,A=!1,E=this.window||"undefined"!=typeof global&&global||this,x,z,K,H=E.document,L=H&&(H.head||H.getElementsByTagName("head")[0]),J=L&&L.getElementsByTagName("base")[0]||null,B={},Z={},P={},ga="addEventListener"in E?{}:{loaded:1,complete:1},S={},ca=S.toString,C,F={},Q={},R=A,M,$=/^\/|^[^:]+:\/\//,da=/(\.)(\.?)(?:$|\/([^\.\/]+.*)?)/g,ha=/\/\*[\s\S]*?\*\/|(?:[^\\])\/\/.*?[\n\r]/g,ia=/require\s*\(\s*["']([^"']+)["']\s*\)|(?:[^\\]?)(["'])/g,T,u;u={m:function(a,b,c){var d;a=g(a,b);
if("."==a.charAt(0))return a;d=e(a);a=(b=d.j)||d.l;a in c.c&&(a=c.c[a].K||a);b&&(0>b.indexOf("/")&&!(b in c.c)&&(a=l(c.N)+"/"+b),a=a+"!"+d.l);return a},f:function(b,c,d,e){function f(a){return u.m(a,g.id,b)}function h(c,d,m){var p;p=d&&function(a){d.apply(C,a)};if(k(c,"String")){if(p)throw Error("require(id, callback) not allowed");m=f(c);c=F[m];if(!(m in F))throw Error("Module not resolved: "+m);return(m=c instanceof a&&c.a)||c}j(u.h(u.f(b,g.id,c,e)),p,m)}var g;g=new a;g.id=c||"";g.ca=e;g.D=d;g.b=
b;g.u=h;h.toUrl=function(a){return u.k(f(a),b).url};g.m=f;return g},B:function(a,b,c){var d,e,f;d=u.f(a,b,C,c);e=d.g;f=m(1,function(a){d.p=a;try{return u.V(d)}catch(b){d.d(b)}});d.g=function(a){j(c||R,function(){e(F[d.id]=Q[d.url]=f(a))})};d.G=function(a){j(c||R,function(){d.a&&(f(a),d.t(Z))})};return d},T:function(a,b,c,d){return u.f(a,c,C,d)},aa:function(a){return a.u},H:function(a){return a.a||(a.a={})},$:function(a){var b=a.q;b||(b=a.q={id:a.id,uri:u.I(a),exports:u.H(a),config:function(){return a.b}},
b.a=b.exports);return b},I:function(a){return a.url||(a.url=u.A(a.u.toUrl(a.id),a.b))},P:function(a){var b,c,d,e,f;b="curl";c="define";d=e=E;if(a&&(f=a.overwriteApi||a.ma,b=a.apiName||a.ia||b,d=a.apiContext||a.ha||d,c=a.defineName||a.ka||c,e=a.defineContext||a.ja||e,z&&k(z,"Function")&&(E.curl=z),z=null,K&&k(K,"Function")&&(E.define=K),K=null,!f)){if(d[b]&&d[b]!=n)throw Error(b+" already exists");if(e[c]&&e[c]!=q)throw Error(c+" already exists");}d[b]=n;e[c]=q},b:function(a){function c(a,d){var f,
m,p,r,n;for(n in a){p=a[n];k(p,"String")&&(p={path:a[n]});p.name=p.name||n;r=h;m=e(l(p.name));f=m.l;if(m=m.j)(r=j[m])||(r=j[m]=b(h),r.c=b(h.c),r.e=[]),delete a[n];if(d){m=p;var v=void 0;m.path=l(m.path||m.location||"");v=m.main||"./main";"."==v.charAt(0)||(v="./"+v);m.K=g(v,m.name+"/");m.b=m.config;m.b&&(m.b=b(h,m.b))}else m={path:l(p.path)};m.Q=f.split("/").length;f?(r.c[f]=m,r.e.push(f)):r.n=u.O(p.path,h)}}function d(a){var b=a.c;a.M=RegExp("^("+a.e.sort(function(a,c){return b[c].Q-b[a].Q}).join("|").replace(/\/|\./g,
"\\$&")+")(?=\\/|$)");delete a.e}var f,h,j,m;"baseUrl"in a&&(a.n=a.baseUrl);"main"in a&&(a.K=a.main);"preloads"in a&&(a.na=a.preloads);"pluginPath"in a&&(a.N=a.pluginPath);if("dontAddFileExt"in a||a.i)a.i=RegExp(a.dontAddFileExt||a.i);f=x;h=b(f,a);h.c=b(f.c);j=a.plugins||{};h.plugins=b(f.plugins);h.s=b(f.s,a.s);h.r=b(f.r,a.r);h.e=[];c(a.packages,w);c(a.paths,A);for(m in j)a=u.m(m+"!","",h),h.plugins[a.substr(0,a.length-1)]=j[m];j=h.plugins;for(m in j)if(j[m]=b(h,j[m]),a=j[m].e)j[m].e=a.concat(h.e),
d(j[m]);for(m in f.c)h.c.hasOwnProperty(m)||h.e.push(m);d(h);return h},S:function(a){var b;(b=a&&a.preloads)&&0<b.length&&j(R,function(){R=u.h(u.f(x,C,b,w))})},k:function(a,b){var c,d,e,f;c=b.c;e=$.test(a)?a:a.replace(b.M,function(a){d=c[a]||{};f=d.b;return d.path||""});return{b:f||x,url:u.O(e,b)}},O:function(a,b){var c=b.n;return c&&!$.test(a)?l(c)+"/"+a:a},A:function(a,b){return a+((b||x).i.test(a)?"":".js")},J:function(a,b,c){var d=H.createElement("script");d.onload=d.onreadystatechange=function(c){c=
c||E.event;if("load"==c.type||ga[d.readyState])delete P[a.id],d.onload=d.onreadystatechange=d.onerror="",b()};d.onerror=function(){c(Error("Syntax or http error: "+a.url))};d.type=a.L||"text/javascript";d.charset="utf-8";d.async=!a.da;d.src=a.url;P[a.id]=d;L.insertBefore(d,J);return d},W:function(a){var b=[],c;("string"==typeof a?a:a.toSource?a.toSource():a.toString()).replace(ha,"").replace(ia,function(a,d,e){e?c=c==e?C:c:c||b.push(d);return""});return b},Z:function(a){var b,c,d,e,f,h;f=a.length;
d=a[f-1];e=k(d,"Function")?d.length:-1;2==f?k(a[0],"Array")?c=a[0]:b=a[0]:3==f&&(b=a[0],c=a[1]);!c&&0<e&&(h=w,c=["require","exports","module"].slice(0,e).concat(u.W(d)));return{id:b,p:c||[],v:0<=e?d:function(){return d},o:h}},V:function(a){var b;b=a.v.apply(a.o?a.a:C,a.p);b===C&&a.a&&(b=a.q?a.a=a.q.a:a.a);return b},C:function(a,b){a.v=b.v;a.o=b.o;a.D=b.p;u.h(a)},h:function(b){function c(a,b,d){g[b]=a;d&&r(a,b)}function d(c,e){var f,h,g,p;f=m(1,function(a){h(a);l(a,e)});h=m(1,function(a){r(a,e)});
g=u.X(c,b);(p=g instanceof a&&g.a)&&h(p);j(g,f,b.d,b.a&&function(a){g.a&&(a==B?h(g.a):a==Z&&f(g.a))})}function e(){b.g(g)}var f,h,g,p,k,r,l;g=[];h=b.D;p=h.length;0==h.length&&e();r=m(p,c,function(){b.G&&b.G(g)});l=m(p,c,e);for(f=0;f<p;f++)k=h[f],k in T?(l(T[k](b),f,w),b.a&&b.t(B)):k?d(k,f):l(C,f,w);return b},Y:function(a){u.I(a);u.J(a,function(){var b=M;M=C;a.ga!==A&&(!b||b.F?a.d(Error(b&&b.F||"define() missing or duplicated: "+a.url)):u.C(a,b))},a.d);return a},X:function(b,c){var d,f,h,g,m,p,k,r,
l,n,v;d=c.m;f=c.ca;h=c.b||x;g=e(d(b));k=g.l;m=g.j||k;r=u.k(m,h);if(g.j)p=m;else if(p=r.b.moduleLoader||r.b.la)k=m,m=p,r=u.k(p,h);m in F?l=F[m]:r.url in Q?l=F[m]=Q[r.url]:(l=u.B(r.b,m,f),l.url=u.A(r.url,r.b),F[m]=Q[r.url]=l,u.Y(l));m==p&&(n=new a,v=h.plugins[p]||h,j(l,function(a){var b,c,e;e=a.dynamic;k="normalize"in a?a.normalize(k,d,l.b)||"":d(k);c=p+"!"+k;b=F[c];if(!(c in F)){b=u.T(v,c,k,f);e||(F[c]=b);var h=function(a){b.g(a);e||(F[c]=a)};h.resolve=h;h.reject=h.error=b.d;a.load(k,b.u,h,v)}n!=b&&
j(b,n.g,n.d,n.t)},n.d));return n||l},ba:function(){var a;if(!k(E.opera,"Opera"))for(var b in P)if("interactive"==P[b].readyState){a=b;break}return a}};T={require:u.aa,exports:u.H,module:u.$};n.version="0.7.3";n.config=f;q.amd={plugins:w,jQuery:w,curl:"0.7.3"};x={n:"",N:"curl/plugin",i:/\?|\.js\b/,s:{},r:{},plugins:{},c:{},M:/$^/};z=E.curl;K=E.define;!z||k(z,"Function")?u.P():(E.curl=C,f(z));F.curl=n;F["curl/_privileged"]={core:u,cache:F,config:function(){return x},_define:p,_curl:n,Promise:a};var aa=
this.document;define("curl/plugin/js",["curl/_privileged"],function(a){function b(c,d,e){function f(){j||(h<new Date?e():setTimeout(f,10))}var h,j,g;h=(new Date).valueOf()+(c.fa||3E5);e&&c.a&&setTimeout(f,10);g=a.core.J(c,function(){j=w;c.a&&(c.w=t(c.a));!c.a||c.w?d(g):e()},function(a){j=w;e(a)})}function c(a,d){b(a,function(){var b=e.shift();j=0<e.length;b&&c.apply(null,b);d.g(a.w||w)},function(a){d.d(a)})}var d={},e=[],f=aa&&aa.createElement("script").async==w,h,j;h=a.Promise;return{dynamic:w,normalize:function(a,
b){var c=a.indexOf("!");return 0<=c?b(a.substr(0,c))+a.substr(c):b(a)},load:function(a,g,m,p){function k(a){(m.error||function(a){throw a;})(a)}var r,l,n,v,s;r=0<a.indexOf("!order");l=a.indexOf("!exports=");n=0<l&&a.substr(l+9);v="prefetch"in p?p.prefetch:w;a=r||0<l?a.substr(0,a.indexOf("!")):a;g=g.toUrl(a);s=g.lastIndexOf(".")<=g.lastIndexOf("/")?g+".js":g;s in d?d[s]instanceof h?d[s].z(m,k):m(d[s]):(a={name:a,url:s,da:r,a:n,fa:p.timeout},d[s]=p=new h,p.z(function(a){d[s]=a;m(a)},k),r&&!f&&j?(e.push([a,
p]),v&&(a.L="text/cache",b(a,function(a){a&&a.parentNode.removeChild(a)},function(){}),a.L="")):(j=j||r,c(a,p)))}}});var ea="createElement",Y=this.setTimeout,I=this.document,O,ja=I&&I.createStyleSheet&&!(10<=I.documentMode),X=[],W=[],U=[],fa=12,ba,V="HTTP or network error.",N={};I&&(O=I.head||I.getElementsByTagName("head")[0],ba=ja?r:G);define("curl/plugin/css",{normalize:function(a,b){var c,d;if(!a)return a;c=a.split(",");d=[];for(var e=0,f=c.length;e<f;e++)d.push(b(c[e]));return d.join(",")},load:function(a,
b,c,d){function e(a){1<j.length&&h.push(a);0==--m&&c(1==j.length?a:h)}function f(a){(c.d||function(a){throw a;})(a)}var h,j,g,m,p;h=[];j=(a||"").split(",");g=d.cssWatchPeriod||50;d=d.cssNoWait;m=j.length;for(p=0;p<j.length;p++){a=j[p];var k;a=b.toUrl(a);a=a.lastIndexOf(".")<=a.lastIndexOf("/")?a+".css":a;d?(k=s(),k.href=a,O.appendChild(k),e(k.sheet||k.styleSheet)):ba(a,e,f,g)}},"plugin-builder":"./builder/css",pluginBuilder:"./builder/css"})}).call(this);var JSON;JSON||(JSON={});
(function(){function d(a){return 10>a?"0"+a:a}function k(b){e.lastIndex=0;return e.test(b)?'"'+b.replace(e,function(b){var c=a[b];return"string"===typeof c?c:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function l(a,d){var e,h,g,q,t=c,s,r=d[a];r&&("object"===typeof r&&"function"===typeof r.toJSON)&&(r=r.toJSON(a));"function"===typeof j&&(r=j.call(d,a,r));switch(typeof r){case "string":return k(r);case "number":return isFinite(r)?String(r):"null";case "boolean":case "null":return String(r);
case "object":if(!r)return"null";c+=b;s=[];if("[object Array]"===Object.prototype.toString.apply(r)){q=r.length;for(e=0;e<q;e+=1)s[e]=l(e,r)||"null";g=0===s.length?"[]":c?"[\n"+c+s.join(",\n"+c)+"\n"+t+"]":"["+s.join(",")+"]";c=t;return g}if(j&&"object"===typeof j){q=j.length;for(e=0;e<q;e+=1)"string"===typeof j[e]&&(h=j[e],(g=l(h,r))&&s.push(k(h)+(c?": ":":")+g))}else for(h in r)Object.prototype.hasOwnProperty.call(r,h)&&(g=l(h,r))&&s.push(k(h)+(c?": ":":")+g);g=0===s.length?"{}":c?"{\n"+c+s.join(",\n"+
c)+"\n"+t+"}":"{"+s.join(",")+"}";c=t;return g}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+d(this.getUTCMonth()+1)+"-"+d(this.getUTCDate())+"T"+d(this.getUTCHours())+":"+d(this.getUTCMinutes())+":"+d(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var g=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c,b,a={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},j;"function"!==typeof JSON.stringify&&(JSON.stringify=function(a,d,e){var h;b=c="";if("number"===typeof e)for(h=0;h<e;h+=1)b+=" ";else"string"===typeof e&&(b=e);if((j=d)&&"function"!==typeof d&&("object"!==typeof d||"number"!==typeof d.length))throw Error("JSON.stringify");return l("",{"":a})});
"function"!==typeof JSON.parse&&(JSON.parse=function(a,b){function c(a,d){var e,h,j=a[d];if(j&&"object"===typeof j)for(e in j)Object.prototype.hasOwnProperty.call(j,e)&&(h=c(j,e),void 0!==h?j[e]=h:delete j[e]);return b.call(a,d,j)}var d;a=String(a);g.lastIndex=0;g.test(a)&&(a=a.replace(g,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+a+")"),"function"===typeof b?c({"":d},""):d;throw new SyntaxError("JSON.parse");})})();window.JSON=JSON;
define("UWA/Core",function(){var d,k=Function("return this")(),l=Object.prototype.hasOwnProperty,g=Object.prototype.toString,e=window.UWA||{},c=function(){var a=g.call(arguments),b;~a.indexOf("Arguments")?b=function(b){return g.call(b)===a}:(a=g.call([]),b=function(b){try{return g.apply(b,b)!==a}catch(c){return!1}});return b}(),b;b=function(a,b){return n[b].split("://")[1]};var a,j=k.document,j=j&&j.location&&"https:"===j.location.protocol?"https://":"http://",m=e.hosts,n={netvibes:"netvibes.com",
uwa:"uwa.{netvibes}",exposition:"{uwa}",ecosystem:"eco.{netvibes}"};for(a in n)l.call(n,a)&&(n[a]=m&&l.call(m,a)?m[a]:j+n[a].replace(/\{(\w+)\}/g,b));b=n;var f,j=e.paths;a={lib:"/lib/",js:"/lib/UWA/js/",css:"/lib/c/UWA/assets/css/",img:"/lib/c/UWA/assets/img/"};for(f in a)l.call(a,f)&&(j&&l.call(j,f))&&(a[f]=j[f]);f=!!e.debug;var h=function(a){if(!a||"object"!==d.typeOf(a))return!1;try{if(a.constructor&&!l.call(a,"constructor")&&!l.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}for(var c in a)if(!l.call(a,
c))return!1;return!0},p;p=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b)}:function(a,b){var c,d,e=!1;c=0;for(d=a.length;c<d;c++)if(a[c]===b){e=!0;break}return e?c:-1};var q=function(a,b,c,e){var f,h,j,m;if(a===b)j=0!==a||1/a===1/b;else if(null==a||null==b)j=a===b;else if(f=g.call(a),f!==g.call(b))j=!1;else if("[object String]"===f)j=String(a)===String(b);else if("[object Number]"===f)j=a!=+a?b!=+b:0==a?1/a==1/b:a==+b;else if("[object Date]"===f||"[object Boolean]"===
f)j=+a===+b;else if("[object RegExp]"===f)j=a.source===b.source&&a.global===b.global&&a.multiline===b.multiline&&a.ignoreCase===b.ignoreCase;else if("object"!==typeof a||"object"!==typeof b)j=!1;else{for(h=c.length;h--;)c[h]===a&&(j=e[h]===b);if(void 0===j){c.push(a);e.push(b);if("[object Array]"===f){f=a.length;for(j=f===b.length;j&&0<f;)f--,j=q(a[f],b[f],c,e)}else if(j=a.constructor,f=b.constructor,j!==f&&!("[object Function]"===g.call(j)&&j instanceof j&&"[object Function]"===g.call(f)&&f instanceof
f))j=!1;else{f=0;j=!0;for(m in a)if(d.owns(a,m)&&(f++,j=d.owns(b,m)&&q(a[m],b[m],c,e),!j))break;if(j){for(m in b)if(d.owns(b,m)&&!f--)break;j=!f}}c.pop();e.pop()}}return j},t,s,r={};d={version:"1.3.RC4",hosts:b,paths:a,debug:f,namespace:function(a,b,c,e){c=c||k;var f,h,j,g=a.split("/");f=0;for(h=g.length;f<h;f++){a=g[f];j=!!c[a];if(f===h-1)if(j)if(e)b=c[a]=d.extend(c[a],b,!0);else throw d.log('Duplicate NameSpace "'+g.join(".")+'" into "'+c+'"'),Error('Duplicate NameSpace "'+g.join(".")+'" into "'+
c+'"');else c[a]=b;else j||(c[a]={});c=c[a]}return b},extend:function(a,b,c){var e;b=b||{};for(e in b)if(l.call(b,e))if(c&&d.is(b[e],"plain"))d.is(a[e],"plain")||(a[e]={}),d.extend(a[e],b[e],c);else try{a[e]=b[e]}catch(f){}return a},merge:function(a,b){for(var c in b)if(l.call(b,c)&&(void 0===a[c]||null===a[c]))a[c]=b[c];return a},clone:function(a,b){var c,e,f;c=!0!==b&&!1!==b?!0:b;switch(d.typeOf(a)){case "array":if(c){c=[];e=0;for(f=a.length;e<f;e++)c[e]=d.clone(a[e],!0)}else c=a.slice();break;
case "object":if(c)for(e in c={},a)l.call(a,e)&&(c[e]=d.clone(a[e],!0));else c=d.extend({},a);break;case "date":c=new Date(a);break;case "element":c=a.cloneNode(c);break;default:c=a}return c},typeOf:function(a){var b=e.Class||d.Class,f=typeof a;return"undefined"===f?!1:"number"===f?isNaN(a)?!1:f:"function"===f?a instanceof RegExp?"regexp":b&&a.extend===b.extend?"class":f:"object"===f?null===a?!1:a.nodeType?9===a.nodeType?"document":"element":void 0!==a.setInterval?"window":a instanceof Array?"array":
a instanceof Date?"date":a instanceof RegExp?"regexp":a instanceof Number?"number":a instanceof Boolean?"boolean":a instanceof Error?"error":c(a)?"arguments":void 0!==a.cancelBubble||a.stopPropagation?"event":f:f},is:function(a,b){var c,e;if(void 0===b)c="number"===typeof a?!isNaN(a):void 0!==a&&null!==a;else if(b="array"===d.typeOf(b)?b:[b],c=!1,-1!==p(b,"finite")&&(c=isFinite(a)),!c&&-1!==p(b,"plain")&&(c=h(a)),!c&&!1!==(e=d.typeOf(a)))c=-1!==p(b,e);return c},equals:function(a,b){return q(a,b,[],
[])},owns:function(a,b){return d.is(a)&&l.call(a,b)},log:function(a){k.console?k.console.log(a):k.opera&&k.opera.postError&&k.opera.postError(a)},i18n:function(a,b){b=b||(k.navigator?k.navigator.language||k.navigator.systemLanguage:"default");t=r[b]=r[b]||{};return s="object"===typeof a?d.extend(t,a):t[a]||a}};define.amd&&define.amd.curl&&(k.require||k.curl)({apiName:"require",paths:{UWA:d.hosts.uwa+d.paths.js}});return d.namespace("UWA",d,k,!0)});
define("UWA/Class",["UWA/Core"],function(d){function k(c,b){var a=function(){var a,d,e=null!==this&&void 0!==this;e&&(d=this._parent,this._parent=c);a=b.apply(this,arguments);e&&(this._parent=d);return a};a._original=b;return a}var l=!1,g=/xyz/.test(function(){d.xyz()})?/\b_parent\b/:/^/,e=function(){};e.extend=function(){function c(a,b){return function(){a.apply(this,arguments);b.apply(this,arguments)}}var b,a,j,m,n,f,h,p=this.prototype,q="function"===typeof this&&this;l=!0;j=new this;l=!1;b=0;for(a=
arguments.length;b<a;b+=1){n=arguments[b];d.is(n,["class","function"])?(h=n,q&&(h=c(q,h)),n=n.prototype):(h=n.init,delete n.init);h&&(g.test(h)&&(h=k(q,h._original||h)),q=h);for(m in n)f=d.typeOf(n[m]),"function"===f&&g.test(n[m])?j[m]=k("function"===typeof p[m]?p[m]:e,n[m]._original||n[m]):"object"===f&&d.is(p[m],"object")?(j[m]=d.clone(p[m]),d.extend(j[m],n[m],!0)):j[m]=n[m];p=j}h||(h=q);b=function(){!l&&h&&h.apply(this,arguments)};b.prototype=j;b.parent=this;j.constructor=b;b.extend=e.extend;b.singleton=
e.singleton;return b};e.singleton=function(){function c(b){a[b]=function(){if(!g){if("throw"===a.uninitializedCalls)throw Error("Singleton called before being initialized");if("ignore"===a.uninitializedCalls)return;a.init()}return a[b].apply(this,arguments)}}var b,a,d=this.extend.apply(this,arguments),e=d.prototype,g=!1,f=[];l=!0;a=new d;l=!1;for(b in e)"function"===typeof e[b]&&("init"!==b&&"constructor"!==b)&&(f.push(b),c(b));a.init=function(){if(g)throw Error("Singleton is already initialized");
g=!0;var b,c;b=0;for(c=f.length;b<c;b++)delete a[f[b]];d.apply(this,arguments);return this};return a};return d.namespace("Class",e,d)});
define("UWA/Class/Options",["UWA/Core","UWA/Class"],function(d,k){return d.namespace("Options",{setOptions:function(k){k=k||{};this.hasOwnProperty("options")||(this.options=d.clone(this.defaultOptions||this.options||{}));k.events&&this.addEvents&&this.addEvents(k.events);d.extend(this.options,k,!0);return this},setOption:function(d,g){var e={};e[d]=g;return this.setOptions(e)}},k)});
define("UWA/Class/Debug",["UWA/Core","UWA/Class"],function(d,k){return d.namespace("Debug",{debugMode:!1,setDebugMode:function(d){this.debugMode=!0===d||"true"===d;return this},log:function(k){!0===this.debugMode&&d.log(k);return this}},k)});
define("UWA/Utils",["UWA/Core","UWA/Function","UWA/String","UWA/Array","UWA/Date"],function(d){var k,l=/^(?:https?:)?\/\//,g=/<(DOCTYPE|xml)[^><]*>|<.(DOCTYPE|xml)[^><]*>/g,e=/(<(style|script)[^>]*>)([\u0001-\uFFFF]*?)(<\/(style|script)>)/img,c=/<!\[CDATA\[/,b=function(b){b=b.replace(a,"");return b=b.replace(j,"<$1$2$4>")},a=RegExp("</?(script|embed|object|frameset|frame|iframe|meta|link|style)(.|\n)*?>","img"),j=RegExp("<([a-z][a-z0-9]*)(?:[^>]*(s(src|href|title|style|alt|height|width|data-([a-z][a-z0-9]*))=['\"][^'\"]*['\"]))?[^>]*?(/?)>",
"im"),m=window.btoa||function(a){for(var b,c,d,e,j,g,m=a.length,k="",l=0;l<m;)b=a.charCodeAt(l++),c=a.charCodeAt(l++),d=a.charCodeAt(l++),e=b>>2,b=(b&3)<<4|c>>4,j=(c&15)<<2|d>>6,g=d&63,isNaN(c)?j=g=64:isNaN(d)&&(g=64),k=k+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(j)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g);
return k},n=window.atob||function(a){var b,c,d,e,j,g,m="",k=0;a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");b=a.length;if(1===b%4)throw Error("InvalidCharacterError: DOM Exception 5");for(;k<b;)c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(k++)),d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(k++)),j="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(k++)),g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(k++)),
c=c<<2|d>>4,d=(d&15)<<4|j>>2,e=(j&3)<<6|g,m+=String.fromCharCode(c),64!==j&&(m+=String.fromCharCode(d)),64!==g&&(m+=String.fromCharCode(e));return m};k={buildUrl:function(a,b){var c,d,e=String(a).split("://"),j=e[0],g=e[1].split("/"),m=g[0],e="";if("//"===b.substring(0,2))a=j+":"+b;else if(1<b.split("://").length)a=b;else if("/"===b.substring(0,1))a=j+"://"+m+b;else{c=1;for(d=g.length-1;c<d;c++)e+="/"+g[c];var j=j+"://"+m,e=e+"/"+b,k=[];e.replace(/^(\.\.?(\/|$))+/,"").replace(/\/(\.(\/|$))+/g,"/").replace(/\/\.\.$/,
"/../").replace(/\/?[^\/]*/g,function(a){"/.."===a?k.pop():k.push(a)});e=k.join("").replace(/^\//,"/"===e.charAt(0)?"/":"");a=j+e}return a},parseUrl:function(a){var b="source subprotocol protocol authority user password domain port path directoryPath fileName query anchor".split(" "),c=RegExp("^(?:(?:(?:([^#.:]+):)?([^#.:]+):)?//)?((?:([^:]+)(?::(.*?))?@)?([^:/?#]*)(?::(\\d*))?)?((/(?:[^?#](?![^?#/]*\\.[^?#/.]+(?:[\\?#]|$)))*/?)?([^?#/]*))?(?:\\?([^#]*))?(?:#(.*))?").exec(a),d={};for(a=0;a<b.length;a++)d[b[a]]=
c[a]||"";d.subprotocol&&(d.source=d.source.substr(d.subprotocol.length+1));d.port||(d.port="https"===d.protocol?"443":"80");d.directoryPath&&0<d.directoryPath.length&&(d.directoryPath=d.directoryPath.replace(/\/?$/,"/"));d.domain=d.domain.toLocaleLowerCase();d.protocol=d.protocol.toLocaleLowerCase();return d},composeUrl:function(a){var b="";a.protocol&&(b=a.protocol+"://",a.subprotocol&&(b=a.subprotocol+":"+b));if(a.domain){if(b+=a.domain,a.port&&("http"!==a.protocol||80!==parseInt(a.port,10))&&("https"!==
a.protocol||443!==parseInt(a.port,10)))b+=":"+a.port}else a.authority&&(b+=a.authority);a.path&&(b+=a.path);a.query&&(b+="?"+a.query);a.anchor&&(b+="#"+a.anchor);return b},matchUrl:function(a,b){var c,d,e=!1,e=k.isAbsoluteUrl(a),j=k.isAbsoluteUrl(b);!e&&!j?e=!0:(e?j||(b=k.buildUrl(a,b)):a=k.buildUrl(b,a),c=k.parseUrl(a),d=k.parseUrl(b),e=["domain","protocol","port"].every(function(a){return c[a]===d[a]}));return e},isAbsoluteUrl:function(a){return l.test(a)},encodeUrl:function(a){return encodeURIComponent(a).replace(/\./g,
"%2e")},parseQuery:function(a){a=a.substring(a.indexOf("?")+1).split(/[&;]/);var b={};a.length&&a.forEach(function(a){var c=a.indexOf("=")+1,e=c?a.substr(c):"",f=c?a.substr(0,c-1).match(/([^\]\[]+|(\B)(?=\]))/g):[a],j=b;f&&(e=decodeURIComponent(e),f.forEach(function(a,b){a=decodeURIComponent(a);var c=j[a];b<f.length-1?j=j[a]=c||{}:Array.isArray(c)?c.push(e):j[a]=d.is(c)?[c,e]:e}))});return b},toQueryString:function(a,b){var c,e,j,g,m=d.is;if(m(a,"string"))g=a;else if(m(a.toQueryString,"function"))g=
a.toQueryString();else{g=[];for(c in a)a.hasOwnProperty(c)&&(e=a[c],b&&(c=b+"["+c+"]"),m(e)&&(m(e,"object")||m(e,"array")?j=k.toQueryString(e,c):m(e,"function")||(j=k.encodeUrl(c)+"="+k.encodeUrl(e))),j&&g.push(j),j=void 0);g=g.join("&")}return g},getQueryString:function(a,b,c){b=b.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");return(a=RegExp(b+"=([^&#]*)").exec(a))?decodeURIComponent(a[1]):c},loadXml:function(a,b){var d,j,m;if("object"===typeof a&&a.nodeType)d=a;else if(a=a.replace(g,""),a=a.replace(e,
function(){var a=arguments,b=a[1],d=a[3],a=a[4];c.test(d)||(d="<![CDATA[\n"+d+"\n]]\x3e");return b+d+a}),window.DOMParser){if(d=new window.DOMParser,d=d.parseFromString(a,"application/xml"),j=d.getElementsByTagName("parsererror")[0])throw Error("Invalid in XML: "+(j.textContent||j.innerText));}else if(d=new window.ActiveXObject("MSXML2.DOMDocument"),d.setProperty("SelectionLanguage","XPath"),d.validateOnParse=!1,d.resolveExternals=!1,d.preserveWhiteSpace=!1,d.async=!1,d.loadXML(a),0!==d.parseError.errorCode)throw Error("Invalid in XML Line "+
d.parseError.line+": "+d.parseError.reason);b&&(window.XSLTProcessor?(j=new window.XSLTProcessor,j.importStylesheet(k.loadXml(b)),d=j.transformToDocument(d,document)):(j=new window.ActiveXObject("Msxml2.FreeThreadedDOMDocument"),j.loadXML(k.xmlToString(b)),m=new window.ActiveXObject("Msxml2.XSLTemplate"),m.stylesheet=j,j=m.createProcessor(),j.input=d,j.transform(),d=k.loadXml(j.output)));return d},loadHtml:function(a){var c,d,e;if(window.DOMParser)try{c=(new window.DOMParser).parseFromString(a,"text/html")}catch(j){}if(!c&&
document.implementation.createHTMLDocument)try{c=document.implementation.createHTMLDocument(""),d=c.documentElement,d.innerHTML=a,e=d.firstElementChild,1===d.childElementCount&&"html"===e.localName.toLowerCase()&&c.replaceChild(e,d)}catch(g){c=null}if(!c&&window.ActiveXObject){a=b(a);try{c=new window.ActiveXObject("htmlfile"),c.write(a),c.close()}catch(m){c=null}}c||(a=b(a),d=document.createElement("iframe"),d.style.display="none",document.body.appendChild(d),c=d.contentDocument||d.contentWindow.document,
c.write(a),c.close(),document.body.removeChild(d));return c},xmlToHtml:function(a){"string"===typeof a&&(a=k.loadXml(a));9===a.nodeType&&(a=a.childNodes[0]);var b,c,d=a.nodeName.toLowerCase(),e=document.createElement(d),j=a.childNodes,g=a.attributes||[];a=0;for(c=g.length;a<c;a++)b=g[a],e.setAttribute(b.name,b.value);a=0;for(c=j.length;a<c;a++)switch(b=j[a],b.nodeType){case 1:e.appendChild(k.xmlToHtml(b));break;case 3:"style"===d&&e.styleSheet?e.styleSheet.cssText=b.nodeValue:e.appendChild(document.createTextNode(b.nodeValue));
break;case 4:case 8:"script"===d?e.text=b.nodeValue:e.appendChild(document.createComment(b.nodeValue))}return e},xmlToString:function(a,b){var c,d,e=0;"string"===typeof a?c=a:window.XMLSerializer?(c=new window.XMLSerializer,c=c.serializeToString(a)):c=a.xml;b&&(d="",c=c.replace(/(>)(\s+)?(<)(\/*)/g,"$1\r\n$3$4"),c.split("\r\n").forEach(function(a){var b,c=0,f="";a.match(/.+<\/\w[^>]*>$/)?c=0:a.match(/^<\/\w/)?0!==e&&(e-=1):a.match(/^<\w[^>]*[^\/]>.*$/)&&(c=1);for(b=0;b<e;b++)f+="  ";d+=f+a+"\r\n";
e+=c}),c=d);return c},setCss:function(a,b,c,d){var e,j,g,m,l;c=(c||"").trim();b=Array.isArray(b)?b.join("\n"):String(b);a=a||k.getCheckSum(b);b=b.replace(/\/\*([^*\/])+?\*\//g,"");e=c.split(" ");e.push(".module");e.forEach(function(a){b=b.replace(RegExp("(([a-zA-z#]+)?"+a+"([ ,{]))","g"),"$3")});b=b.replace(/\n/g," ").replace(/\}/g,"}\n").split("\n");e=0;for(j=b.length;e<j;e++){l=b[e].trim();if((g=l.match(/url\(\s*[\'"]?(([^\\\\\'", \(\)]*(\\\\.)?)+)[\'"]?\s*\)/))&&g[2])g=g[2],"//"===g.substring(0,
2)?(m=("https:"===document.location.protocol?"https:":"http:")+g,l=l.replace(g,m)):"http"!==g.substring(0,4)&&(m=d.substring(0,d.lastIndexOf("/"))+("/"===g.substring(0,1)?"":"/")+g,l=l.replace(g,m));if(g=l.match(/([a-zA-z0-9\.\-, :#>'"\=\[\]\*]*)\{.*?\}/))g=g[1],m=" "+g,m.test(" body")?m=m.test(" html > body")?m.replace(/ html > body/g," html > body "+c):m.replace(/ body/g," "+c+" "):m.test(" html")?m=m.replace(/ html/g," html "+c+" "):m.test(c)||(m=c+m.replace(m,m.replace(/,/g,", "+c+" "))),l=l.replace(g,
m);b[e]=l}b=b.join("\n").trim().replace(/\s{2,}/g," ");c=document.getElementById(a);c||(c=document.createElement("style"),c.setAttribute("id",a),c.setAttribute("type","text/css"),a=document.getElementsByTagName("head").item(0),a.appendChild(c));c.styleSheet?c.styleSheet.cssText=b:c.appendChild(document.createTextNode(b));return b},toArray:function(a){var b,c,d=[];if("object"===typeof a&&!1===Array.isArray(a))if(void 0!==a.length){b=0;for(c=a.length;b<c;b++)d[b]=a[b]}else for(b in a)a.hasOwnProperty(b)&&
d.push(a[b]);else a&&(d=Array.prototype.slice.call(a));return d},splat:function(a){return d.is(a)?Array.isArray(a)?a:d.is(a,"arguments")?k.toArray(a):[a]:[]},getUUID:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"===a?b:b&3|8).toString(16)})},getCheckSum:function(a,b){a=String(a);var c,d;b=b||305419896;c=0;for(d=a.length;c<d;c++)b+=a.charCodeAt(c)*c;return Math.abs(parseInt(b,10)).toString(36)},getCRC32:function(a){a=String(a);
var b,c,d,e=0,e=0;d=-1;b=0;for(c=a.length;b<c;b++)e=(d^a.charCodeAt(b))&255,e="0x"+"00000000 77073096 EE0E612C 990951BA 076DC419 706AF48F E963A535 9E6495A3 0EDB8832 79DCB8A4 E0D5E91E 97D2D988 09B64C2B 7EB17CBD E7B82D07 90BF1D91 1DB71064 6AB020F2 F3B97148 84BE41DE 1ADAD47D 6DDDE4EB F4D4B551 83D385C7 136C9856 646BA8C0 FD62F97A 8A65C9EC 14015C4F 63066CD9 FA0F3D63 8D080DF5 3B6E20C8 4C69105E D56041E4 A2677172 3C03E4D1 4B04D447 D20D85FD A50AB56B 35B5A8FA 42B2986C DBBBC9D6 ACBCF940 32D86CE3 45DF5C75 DCD60DCF ABD13D59 26D930AC 51DE003A C8D75180 BFD06116 21B4F4B5 56B3C423 CFBA9599 B8BDA50F 2802B89E 5F058808 C60CD9B2 B10BE924 2F6F7C87 58684C11 C1611DAB B6662D3D 76DC4190 01DB7106 98D220BC EFD5102A 71B18589 06B6B51F 9FBFE4A5 E8B8D433 7807C9A2 0F00F934 9609A88E E10E9818 7F6A0DBB 086D3D2D 91646C97 E6635C01 6B6B51F4 1C6C6162 856530D8 F262004E 6C0695ED 1B01A57B 8208F4C1 F50FC457 65B0D9C6 12B7E950 8BBEB8EA FCB9887C 62DD1DDF 15DA2D49 8CD37CF3 FBD44C65 4DB26158 3AB551CE A3BC0074 D4BB30E2 4ADFA541 3DD895D7 A4D1C46D D3D6F4FB 4369E96A 346ED9FC AD678846 DA60B8D0 44042D73 33031DE5 AA0A4C5F DD0D7CC9 5005713C 270241AA BE0B1010 C90C2086 5768B525 206F85B3 B966D409 CE61E49F 5EDEF90E 29D9C998 B0D09822 C7D7A8B4 59B33D17 2EB40D81 B7BD5C3B C0BA6CAD EDB88320 9ABFB3B6 03B6E20C 74B1D29A EAD54739 9DD277AF 04DB2615 73DC1683 E3630B12 94643B84 0D6D6A3E 7A6A5AA8 E40ECF0B 9309FF9D 0A00AE27 7D079EB1 F00F9344 8708A3D2 1E01F268 6906C2FE F762575D 806567CB 196C3671 6E6B06E7 FED41B76 89D32BE0 10DA7A5A 67DD4ACC F9B9DF6F 8EBEEFF9 17B7BE43 60B08ED5 D6D6A3E8 A1D1937E 38D8C2C4 4FDFF252 D1BB67F1 A6BC5767 3FB506DD 48B2364B D80D2BDA AF0A1B4C 36034AF6 41047A60 DF60EFC3 A867DF55 316E8EEF 4669BE79 CB61B38C BC66831A 256FD2A0 5268E236 CC0C7795 BB0B4703 220216B9 5505262F C5BA3BBE B2BD0B28 2BB45A92 5CB36A04 C2D7FFA7 B5D0CF31 2CD99E8B 5BDEAE1D 9B64C2B0 EC63F226 756AA39C 026D930A 9C0906A9 EB0E363F 72076785 05005713 95BF4A82 E2B87A14 7BB12BAE 0CB61B38 92D28E9B E5D5BE0D 7CDCEFB7 0BDBDF21 86D3D2D4 F1D4E242 68DDB3F8 1FDA836E 81BE16CD F6B9265B 6FB077E1 18B74777 88085AE6 FF0F6A70 66063BCA 11010B5C 8F659EFF F862AE69 616BFFD3 166CCF45 A00AE278 D70DD2EE 4E048354 3903B3C2 A7672661 D06016F7 4969474D 3E6E77DB AED16A4A D9D65ADC 40DF0B66 37D83BF0 A9BCAE53 DEBB9EC5 47B2CF7F 30B5FFE9 BDBDF21C CABAC28A 53B39330 24B4A3A6 BAD03605 CDD70693 54DE5729 23D967BF B3667A2E C4614AB8 5D681B02 2A6F2B94 B40BBE37 C30C8EA1 5A05DF1B 2D02EF8D".substr(9*
e,8),d=d>>>8^e;return d^-1},base64Encode:function(a){return m(unescape(encodeURIComponent(a)))},base64Decode:function(a){return decodeURIComponent(escape(n(a)))},attempt:function(a,b,c){var e=Array.prototype.slice.call(arguments,3),j;if(d.debug)j=a.apply(c,e);else try{j=a.apply(c,e)}catch(g){b?j=b.apply(c,[g].concat(e)):d.log("Error in Utils.attempt: "+g)}return j},memoize:function(a,b){var c={},d=Array.prototype.slice;b=b||JSON.stringify;return function(){var e=b(d.call(arguments));return c.hasOwnProperty(e)?
c[e]:c[e]=a.apply(this,arguments)}}};return d.namespace("Utils",k,d,!0)});
define("UWA/Dispatcher",["UWA/Core","UWA/Utils","UWA/Class"],function(d,k,l){var g=d.Class.extend({Binding:null,bindings:null,shouldPropagate:!0,active:!0,init:function(){this.bindings=[]},registerListener:function(e,c,b,a){if(!d.is(e,"function")&&(!d.is(e,"object")||!d.is(e.handleEvent,"function")))throw Error("listener is a required param of add() and addOnce() and should be a Function or an object implementing the EventListener interface.");var j=this.indexOfListener(e);if(-1!==j){if(e=this.bindings[j],
e.isOnce!==c)throw Error("You cannot add"+(c?"":"Once")+"() then add"+(!c?"":"Once")+"() the same listener without removing the relationship first.");}else e=new this.Binding(this,e,c,b,a),this.addBinding(e);return e},addBinding:function(d){var c=this.bindings,b=c.length;do--b;while(c[b]&&d.priority<=c[b].priority);c.splice(b+1,0,d)},indexOfListener:function(d){for(var c=this.bindings,b=c.length;b--;)if(c[b].listener===d)return b;return-1},add:function(d,c,b){return this.registerListener(d,!1,c,b)},
addOnce:function(d,c,b){return this.registerListener(d,!0,c,b)},remove:function(e){var c,b=this.bindings;if(!d.is(e,"function")&&(!d.is(e,"object")||!d.is(e.handleEvent,"function")))throw Error("listener is a required param of remove() and should be a Function or an object implementing the EventListener interface.");c=this.indexOfListener(e);-1!==c&&(b[c].destroy(),b.splice(c,1));return e},removeAll:function(){for(var d=this.bindings,c=d.length;c--;)d[c].destroy();d.length=0},getNumListeners:function(){return this.bindings.length},
getListeners:function(){return this.bindings.map(function(d){return d.listener})},halt:function(){this.shouldPropagate=!1},dispatch:function(d,c){if(this.active){d=k.toArray(d);var b=this.bindings.slice(),a=this.bindings.length;this.shouldPropagate=!0;do a--;while(b[a]&&this.shouldPropagate&&!1!==b[a].execute(d,c));return this.shouldPropagate}},dispose:function(){this.removeAll();this.active=!1;delete this.bindings},toString:function(){return"[Dispatcher active: "+this.active+" numListeners: "+this.getNumListeners()+
"]"}});g.Binding=g.prototype.Binding=l.extend({listener:null,isOnce:!1,context:null,dispatcher:null,priority:0,active:!0,init:function(d,c,b,a,j){this.listener=c;this.isOnce=b;this.context=a;this.dispatcher=d;this.priority=j||0},execute:function(e,c){var b,a=this.listener,j=d.is(this.context)?this.context:c;this.active&&(this.isOnce&&this.detach(),b="function"===typeof a.handleEvent?a.handleEvent.apply(void 0===j?a:j,e||[]):a.apply(j,e||[]));return b},detach:function(){return this.dispatcher&&this.dispatcher.remove(this.listener)},
getListener:function(){return this.listener},dispose:function(){this.detach();this.destroy()},destroy:function(){this.active=!1;delete this.dispatcher;delete this.isOnce;delete this.listener;delete this.context},toString:function(){return"[Dispatcher.Binding isOnce: "+this.isOnce+", active: "+this.active+"]"}});return d.namespace("Dispatcher",g,d)});
define("UWA/Function",["UWA/Core"],function(d){d.merge(Function.prototype,{bind:function(d){function l(){var b;this instanceof l?(b=Object.create(e.prototype),e.apply(b,g.concat(c.call(arguments)))):b=e.call.apply(e,g.concat(c.call(arguments)));return b}var g,e=this,c=Array.prototype.slice;if("function"!==typeof e.apply||"function"!==typeof e.call)return new TypeError;g=c.call(arguments);l.length="function"===typeof e?Math.max(e.length-g.length,0):0;return l}});return d.namespace("Function",Function,
d)});
define("UWA/String",["UWA/Core"],function(d){function k(c){c=c.replace(/\s+/g,"");var b,a,d=!1,e=c.match(/^rgb(a?)\(((?:\d{1,3},)*\d{1,3})\)/);if(e){if(d=e[2].split(",").map(function(a){return parseInt(a,10)}),!e[1]&&3!==d.length||e[1]&&4!==d.length)d=!1}else if(e=c.match(/^#?((?:[a-f0-9]{3}){1,2})$/i)){c=3===e[1].length?1:2;d=[];for(b=0;b<e[1].length;b+=c)a=parseInt(e[1].substr(b,c),16),1===c&&(a=16*a+a),d.push(a)}else"transparent"===c&&(d=[0,0,0,0]);return d}var l,g,e="\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff";if(!String.prototype.trim||
e.trim())e="["+e+"]",l=RegExp("^"+e+e+"*"),g=RegExp(e+e+"*$"),String.prototype.trim=function(){if(void 0===this||null===this)throw new TypeError("can't convert "+this+" to object");return String(this).replace(l,"").replace(g,"")};d.extend(String.prototype,{contains:function(c,b){return b?-1<(b+this+b).indexOf(b+c+b):-1<this.indexOf(c)},test:function(c,b){return("string"===typeof c?RegExp(c,b):c).test(this)},isEmail:function(){return/^([a-zA-Z0-9_.\-+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/.test(this)},
truncate:function(c,b){c=c||30;b=void 0===b?"...":b;return this.length>c?this.slice(0,c-b.length)+b:String(this)},cut:function(c,b){c=c||30;b=void 0===b?"...":b;if(this.length<=c)return String(this);var a,d=-1,e=b.length;for(a=c-e;0<=a;a--)if(-1!==".,;!? ".indexOf(this.charAt(a))){d=a;break}0>d&&(d=c-e);return this.slice(0,d)+b},escapeRegExp:function(){return this.replace(/\\/g,"\\\\").replace(/([\-.*+\?\^$()\[\]{}|])/g,"\\$1")},stripTags:function(){return this.replace(/ on\w+="[^"]*"/g,"").replace(/<(?!\s*\/?\s*(div|br|dt|dd|th|td|p|pre|h1|h2|h3|h4|h5)\b)[^>]*>/gi,
"").replace(/<\/?[^>]+>/gi," ").replace(/^\s+|\s+$/g,"").replace(/\s+/g," ")},stripScripts:function(c){var b="",a=this.replace(/<script[^>]*>([\s\S]*?)<\/script>/gi,function(a,c){b+=c+"\n";return""});!0===c?eval(b):d.is(c,"function")&&c(b,a);return a},escapeHTMLEntities:function(){var c={},b={apos:39,minus:8722,circ:710,tilde:732,Scaron:352,lsaquo:8249,OElig:338,lsquo:8216,rsquo:8217,ldquo:8220,rdquo:8221,bull:8226,ndash:8211,mdash:8212,trade:8482,scaron:353,rsaquo:8250,oelig:339,Yuml:376,yuml:255,
fnof:402,Alpha:913,Beta:914,Gamma:915,Delta:916,Epsilon:917,Zeta:918,Eta:919,Theta:920,Iota:921,Kappa:922,Lambda:923,Mu:924,Nu:925,Xi:926,Omicron:927,Pi:928,Rho:929,Sigma:931,Tau:932,Upsilon:933,Phi:934,Chi:935,Psi:936,Omega:937,alpha:945,beta:946,gamma:947,delta:948,epsilon:949,zeta:950,eta:951,theta:952,iota:953,kappa:954,lambda:955,mu:956,nu:957,xi:958,omicron:959,pi:960,rho:961,sigmaf:962,sigma:963,tau:964,upsilon:965,phi:966,chi:967,psi:968,omega:969,thetasym:977,upsih:978,piv:982,ensp:8194,
emsp:8195,thinsp:8201,zwnj:8204,zwj:8205,lrm:8206,rlm:8207,sbquo:8218,bdquo:8222,dagger:8224,Dagger:8225,hellip:8230,permil:8240,prime:8242,Prime:8243,oline:8254,frasl:8260,euro:8364,image:8465,weierp:8472,real:8476,alefsym:8501,larr:8592,uarr:8593,rarr:8594,darr:8595,harr:8596,crarr:8629,lArr:8656,uArr:8657,rArr:8658,dArr:8659,hArr:8660,forall:8704,part:8706,exist:8707,empty:8709,nabla:8711,isin:8712,notin:8713,ni:8715,prod:8719,sum:8721,lowast:8727,radic:8730,prop:8733,infin:8734,ang:8736,and:8743,
or:8744,cap:8745,cup:8746,"int":8747,there4:8756,sim:8764,cong:8773,asymp:8776,ne:8800,equiv:8801,le:8804,ge:8805,sub:8834,sup:8835,nsub:8836,sube:8838,supe:8839,oplus:8853,otimes:8855,perp:8869,sdot:8901,lceil:8968,rceil:8969,lfloor:8970,rfloor:8971,lang:9001,rang:9002,loz:9674,spades:9824,clubs:9827,hearts:9829,diams:9830,quot:34,amp:38,lt:60,gt:62,nbsp:160,iexcl:161,cent:162,pound:163,curren:164,yen:165,brvbar:166,sect:167,uml:168,copy:169,ordf:170,laquo:171,not:172,shy:173,reg:174,hibar:175,deg:176,
plusmn:177,sup1:185,sup2:178,sup3:179,acute:180,micro:181,para:182,middot:183,cedil:184,ordm:186,raquo:187,frac14:188,frac12:189,frac34:190,iquest:191,Agrave:192,Aacute:193,Acirc:194,Atilde:195,Auml:196,Aring:197,AElig:198,Ccedil:199,Egrave:200,Eacute:201,Ecirc:202,Euml:203,Igrave:204,Iacute:205,Icirc:206,Iuml:207,ETH:208,Ntilde:209,Ograve:210,Oacute:211,Ocirc:212,Otilde:213,Ouml:214,times:215,Oslash:216,Ugrave:217,Uacute:218,Ucirc:219,Uuml:220,Yacute:221,THORN:222,szlig:223,agrave:224,aacute:225,
acirc:226,atilde:227,auml:228,aring:229,aelig:230,ccedil:231,egrave:232,eacute:233,ecirc:234,euml:235,igrave:236,iacute:237,icirc:238,iuml:239,eth:240,ntilde:241,ograve:242,oacute:243,ocirc:244,otilde:245,ouml:246,divide:247,oslash:248,ugrave:249,uacute:250,ucirc:251,uuml:252,yacute:253,thorn:254};return function(){var a,d,e=this;if(e.match(/&([a-z]+;)/gi))for(a in b)b.hasOwnProperty(a)&&(d=a,c[d]||(c[d]=RegExp("&"+d+";","g")),d=c[d],e=e.replace(d,"&#"+b[a]+";"));return e}}(),globToRegex:function(){var c=
this.escapeRegExp().replace(/\\\*/g,".*").replace(/\\\?/g,".").replace(/\\\{/g,"(").replace(/\\\}/g,")").replace(/,/g,"|");return RegExp("^"+c+"$")},escapeHTML:function(){function c(a){return b[a]}var b={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;","/":"&#x2F;"},a=/[&<>"'\/]/g,d=/[<>\/]/g;return function(b){return this.toString().replace(b?d:a,c)}}(),unescapeHTML:function(){var c=document.createElement("div");c.innerHTML=this.stripTags().replace(/"/g,"&quot;");return c.childNodes[0]?
c.childNodes[0].nodeValue:""},ucfirst:function(){return this.charAt(0).toUpperCase()+this.substr(1)},lcfirst:function(){return this.charAt(0).toLowerCase()+this.substr(1)},capitalize:function(){return this.replace(/\b[a-z]/g,function(c){return c.toUpperCase()})},camelCase:function(){return this.toString().replace(/([A-Z]+)/g,function(c,b){return b.substr(0,1).toUpperCase()+b.toLowerCase().substr(1,b.length)}).replace(/[\-_\s](.)/g,function(c,b){return b.toUpperCase()}).replace(/[\-_\s]/g,"").trim()},
unCamelCase:function(c){c=c||"-";return this.toString().replace(/([a-z])([A-Z])/g,"$1"+c+"$2").replace(/\b([A-Z]+)([A-Z])([a-z])/,"$1"+c+"$2$3").toLowerCase()},rgbToHex:function(c){var b=k(this);b&&(b=c?b.map(function(a){return a.toString(16)}):0===b[3]?"transparent":"#"+b.slice(0,3).map(function(a){return("0"+a.toString(16)).slice(-2)}).join(""));return b},hexToRgb:function(c){var b=k(this);b&&!c&&(b=(3===b.length?"rgb(":"rgba(")+b.join(", ")+")");return b},format:function(){var c=arguments;return this.replace(/\{(\d+)\}/g,
function(b,a){return c[a]})},parseRelativeTime:function(c){var b,a,e=new Date,g=d.i18n,e=(new Date(e.getFullYear(),e.getMonth(),e.getDate())).getTime();"number"!==typeof c&&(c=0);a=(b=this.match(/^(\d\d\d\d)\-(\d\d)\-(\d\d) (\d\d):(\d\d):(\d\d)$/))?(new Date(b[1],b[2]-1,b[3],b[4],b[5],b[6])).getTime():this.test(/^\d{13}$/)?parseInt(this,10):this.test(/^\d{10}$/)?1E3*parseInt(this,10):Date.parse(this.replace(/\//g,"-"));c*=3600;b=(new Date-a)/1E3+c;c=(e-a)/1E3+c;return isNaN(b)?!1:60>b?g("less than a minute ago"):
120>b?g("about a minute ago"):2700>b?g("{0} minutes ago").format(Math.round(b/60)):5400>b?g("about an hour ago"):0>c?g("about {0} hours ago").format(Math.round(b/3600)):86400>c?g("yesterday"):g("{0} days ago").format(Math.ceil(c/86400))},makeClickable:function(){var c;c=this.replace(/((\w+:\/\/(\w+(:\w+)?@)?)|www\.)[^\s<$]+/g,function(b){var a=b.replace(/([\.!\?:;\)\]]$)/,"");a.test(/^www\./)&&(a="http://"+a);return'<a href="'+a+'" target="_blank">'+b+"</a>"});return c=c.replace(/([\/:\w\+\_\-]+(\.[\w\+\_\-]+)*@[\w\.\-]+)/g,
function(b){var a=b;b.test(/^[\w]+:\/\//)||(a='<a href="mailto:'+b+'">'+b+"</a>");return a})},highlight:function(){return this}});return d.namespace("String",String,d)});
define("UWA/Array",["UWA/Core","UWA/Function"],function(d){var k=Object.prototype,l=Function.prototype.call.bind(k.hasOwnProperty),g=function(a){a=+a;isNaN(a)?a=0:0!==a&&(Infinity!==a&&-Infinity!==a)&&(a=(0<a||-1)*Math.floor(Math.abs(a)));return a},e=function(a){if(null===a||void 0===a)throw new TypeError(a+" is not a object");return!a[a.length-1]&&a instanceof String&&a?a.split(""):Object.apply(null,[a])},c=!Array.prototype.reduce||6!==[0,1,2,3].reduce(function(a,b){return a+b});!Array.prototype.indexOf||
[0,1].indexOf(1,2);!Array.prototype.lastIndexOf||[0,1].lastIndexOf(0,-3);var b=!l([void 0],0),a=function(a,c){return c in a||b&&a.length&&c<a.length};d.merge(Array,{isArray:function(a){return"[object Array]"===k.toString.call(a)}});d.merge(Array.prototype,{indexOf:function(b,c){var d=0,f=e(this),h=f.length>>>0;if(!h)return-1;1<arguments.length&&(d=Math.min(d,g(c)));d=0<=d?d:Math.max(0,h+d);for(d;d<h;d++)if(a(f,d)&&f[d]===b)return d;return-1},lastIndexOf:function(b,c){var d=e(this),f=d.length>>>0,
h=f-1;if(!f)return-1;1<arguments.length&&(h=Math.min(h,g(c)));for(h=0<=h?h:f-Math.abs(h);0<=h;h--)if(a(d,h)&&b===d[h])return h;return-1},every:function(b,c){var g,f=e(this),h=f.length>>>0;if(!d.is(b,"function"))throw new TypeError(b+" is not a function");for(g=0;g<h;g++)if(a(f,g)&&!b.call(c,f[g],g,f))return!1;return!0},some:function(b,c){var g,f=e(this),h=f.length>>>0;if(!d.is(b,"function"))throw new TypeError(b+" is not a function");for(g=0;g<h;g++)if(a(f,g)&&b.call(c,f[g],g,f))return!0;return!1},
forEach:function(b,c){var g=0,f=e(this),h=f.length>>>0;if(!d.is(b,"function"))throw new TypeError(b+" is not a function");for(;g<h;)a(f,g)&&b.call(c,f[g],g,f),g++},map:function(b,c){var g,f=e(this),h=f.length>>>0,k=Array.apply(null,[h]);if(!d.is(b,"function"))throw new TypeError(b+" is not a function");for(g=0;g<h;g++)a(f,g)&&(k[g]=b.call(c,f[g],g,f));return k},filter:function(b,c){var g,f=e(this),h=f.length>>>0,k=[];if(!d.is(b,"function"))throw new TypeError(b+" is not a function");for(g=0;g<h;g++)a(f,
g)&&b.call(c,f[g],g,f)&&k.push(f[g]);return k}});c&&(Array.prototype.reduce=function(b,c){var g,f=!0,h=0,k=e(this),l=k.length>>>0;if(!d.is(b,"function"))throw new TypeError(b+" is not a function");if(!l&&1===arguments.length)throw new TypeError("reduce of empty array with no initial value");if(2<=arguments.length)g=c;else{do if(a(k,h)&&(g=k[h++],f=!1),++h>=l)throw new TypeError("reduce of empty array with no initial value");while(f)}for(h;h<l;h++)a(k,h)&&(g=b.call(void 0,g,k[h],h,k));return g});d.merge(Array.prototype,
{reduceRight:function(b,c){var g,f=!0,h=e(this),k=h.length>>>0,l=k-1;if(!d.is(b,"function"))throw new TypeError(b+" is not a function");if(!k&&1===arguments.length)throw new TypeError("reduceRight of empty array with no initial value");if(2<=arguments.length)g=c;else{do if(a(h,l)&&(g=h[l--],f=!1),0>--l)throw new TypeError("reduceRight of empty array with no initial value");while(f)}do a(h,l)&&(g=b.call(void 0,g,h[l],l,h));while(l--);return g},equals:function(a){var b,c=this.length;if(!a||c!==a.length)return!1;
for(b=0;b<c;b++)if(this[b]!==a[b])return!1;return!0},detect:function(a,b){var c,d;c=0;for(d=this.length;c<d;c++)if(a.call(b,this[c],c,this))return this[c]},invoke:function(a){var b=Array.prototype.slice.call(arguments,1);return this.map(function(c){return c[a].apply(c,b)})}});return d.namespace("Array",Array,d)});
define("UWA/Date",["UWA/Core"],function(d){Date.now||(Date.now=function(){return(new Date).getTime()});var k=Date,l=k.parse,g=/^(\d{4}|[+\-]\d{6})(?:-(\d{2})(?:-(\d{2}))?)?(?:[T ]([0-9]?[0-9]):(\d{2})(?::(\d{2})(?:\.(\d{3}))?)?(?:(Z)|([+\-])(\d{2})(?::(\d{2}))?)?)?$/,e=[1,4,5,6,7,10,11];k.parse=function(a){var b,c,d;d=0;var f=g.exec(a);if(f){a=0;for(c=e.length;a<c;a++)b=e[a],f[b]=+f[b]||0;f[2]=(+f[2]||1)-1;f[3]=+f[3]||1;"Z"!==f[8]&&void 0!==f[9]&&(d=60*f[10]+f[11],"+"===f[9]&&(d=-d));d=k.UTC(f[1],
f[2],f[3],f[4],f[5]+d,f[6],f[7])}else d=l?l(a):NaN;return d};if(!Date.prototype.toISOString||-1===(new Date(-621987552E5)).toISOString().indexOf("-000001"))Date.prototype.toISOString=function(){var a,b,c,d;if(!isFinite(this))throw new RangeError("Date.prototype.toISOString called on non-finite value.");a=[this.getUTCMonth()+1,this.getUTCDate(),this.getUTCHours(),this.getUTCMinutes(),this.getUTCSeconds()];d=this.getUTCFullYear();d=(0>d?"-":9999<d?"+":"")+("00000"+Math.abs(d)).slice(0<=d&&9999>=d?-4:
-6);for(b=a.length;b--;)c=a[b],10>c&&(a[b]="0"+c);return d+"-"+a.slice(0,2).join("-")+"T"+a.slice(2).join(":")+"."+("000"+this.getUTCMilliseconds()).slice(-3)+"Z"};Date.prototype.toJSON||(Date.prototype.toJSON=function(){if("function"!==typeof this.toISOString)throw new TypeError("toISOString property is not callable");return this.toISOString()});var c=function(a,b,c){return Array((c||2)-String(a).length+1).join(b||0)+a},b=function(a){return parseInt(a,10)},a=d.i18n,j=[a("Sun"),a("Mon"),a("Tue"),
a("Wed"),a("Thu"),a("Fri"),a("Sat")],m=[a("Sunday"),a("Monday"),a("Tuesday"),a("Wednesday"),a("Thursday"),a("Friday"),a("Saturday")],n=[a("Jan"),a("Feb"),a("Mar"),a("Apr"),a("May"),a("Jun"),a("Jul"),a("Aug"),a("Sep"),a("Oct"),a("Nov"),a("Dec")],f=[a("January"),a("February"),a("March"),a("April"),a("May"),a("June"),a("July"),a("August"),a("September"),a("October"),a("November"),a("December")],h=a("%a %b %e %Y %T"),p=[a("AM"),a("PM")],q=[a("am"),a("pm")],t=a("%m/%d/%y"),a=a("%T"),s={a:function(a){return j[a.getDay()]},
A:function(a){return m[a.getDay()]},b:function(a){return n[a.getMonth()]},B:function(a){return f[a.getMonth()]},c:h,C:function(a){return c(b(a.getFullYear()/100))},d:function(a){return c(a.getDate())},D:"%m/%d/%y",e:function(a){return c(a.getDate()," ")},F:"%Y-%m-%d",g:function(a){return c(s.G(a)%100)},G:function(a){var c=a.getFullYear(),d=b(s.V(a));a=b(s.W(a));a>d?c++:0===a&&52<=d&&c--;return c},h:"%b",H:function(a){return c(a.getHours())},I:function(a){return c(a.getHours()%12||12)},j:function(a){a=
new Date(a.getFullYear()+"/"+(a.getMonth()+1)+"/"+a.getDate()+" GMT")-new Date(a.getFullYear()+"/1/1 GMT");a=b(a/6E4/60/24)+1;return c(a,0,3)},l:function(a){return c(a.getHours()%12||12," ")},m:function(a){return c(a.getMonth()+1)},M:function(a){return c(a.getMinutes())},n:"\n",p:function(a){return p[12<=a.getHours()?1:0]},P:function(a){return q[12<=a.getHours()?1:0]},r:"%I:%M:%S %p",R:"%H:%M",s:function(a){return b(a/1E3)},S:function(a){return c(a.getSeconds())},t:"\t",T:"%H:%M:%S",u:function(a){return a.getDay()||
7},U:function(a){var d=b(s.j(a));a=6-a.getDay();return c(b((d+a)/7))},V:function(a){var d=b(s.W(a)),e=(new Date(a.getFullYear()+"/1/1")).getDay(),d=d+(4<e||1>=e?0:1);53===d&&4>(new Date(a.getFullYear()+"/12/31")).getDay()?d=1:0===d&&(d=s.V(new Date(a.getFullYear()-1+"/12/31")));return c(d,0)},w:function(a){return a.getDay()},W:function(a){var d=b(s.j(a));a=7-s.u(a);return c(b((d+a)/7))},x:t,X:a,y:function(a){return c(a.getFullYear()%100)},Y:function(a){return a.getFullYear()},z:function(a,d){var e=
d?0:a.getTimezoneOffset(),f=c(b(Math.abs(e/60))),g=c(e%60);return(0<e?"-":"+")+f+g},Z:function(a,b){var c;b?c="UTC":(c=a.toString().replace(/^.*:\d\d( GMT[+\-]\d+)? \(?([A-Za-z ]+)\)?\d*$/,"$2").replace(/[a-z ]/g,""),4<c.length&&(c=s.z(a)));return c},"%":"%"};Date.prototype.strftime=function(a,b){var c=this,d=c;b&&(d=new Date(+c+6E4*c.getTimezoneOffset()));return a.replace(/%[A-Za-z%]/g,function(a){var e=s[a.slice(1)];return void 0===e?a:"string"===typeof e?"%"!==e&&0<=e.indexOf("%")?c.strftime(e,
b):e:e(d,b)})};return d.namespace("Date",Date,d)});
define("UWA/Class/Events",["UWA/Core","UWA/Class","UWA/Dispatcher","UWA/Utils"],function(d,k,l,g){function e(c,b,a){var d=c._dispatchers,e=d&&d[b]||new l;a||(d||(d=c._dispatchers=Object.create(null)),d[b]=e);return e}return d.namespace("Events",{dispatchEvent:function(c,b,a){var d,m;void 0===a&&(a=this);b=g.splat(b);d=e(this,c);"function"===typeof this[c]&&d.addOnce(this[c],a,1);"onAnyEvent"!==c&&this.hasEvent("onAnyEvent")?(m=e(this,"onAnyEvent"),"function"===typeof this.onAnyEvent&&m.addOnce(this.onAnyEvent,
a),m.addOnce(function(){d.dispatch(b,a)}),m.dispatch([c].concat(b),a)):d.dispatch(b,a);return this},dispatchAsEventListener:function(c,b,a){var d=this;void 0===a&&(a=d);b=g.splat(b);return function(e){d.dispatchEvent(c,[e].concat(b),a)}},addEvent:function(c,b,a,d){e(this,c).add(b,a,d);return this},addEventOnce:function(c,b,a,d){e(this,c).addOnce(b,a,d);return this},addEvents:function(c){for(var b in c)c.hasOwnProperty(b)&&this.addEvent(b,c[b]);return this},removeEvent:function(c,b){var a,d=this._dispatchers,
e=d&&d[c];if(c)e&&(b?e.remove(b):(e.removeAll(),delete d[c]));else for(a in d)this.removeEvent(a);return this},removeEvents:function(c){if(c)for(var b in c)c.hasOwnProperty(b)&&this.removeEvent(b,c[b]);else this.removeEvent();return this},hasEvent:function(c,b){return!(!e(this,c,!0).getNumListeners()&&!(b?0:this[c]))}},k)});
define("UWA/Utils/Client",["UWA/Core","UWA/Utils"],function(d,k){var l,g=Function("return this")(),e=!!g.window,c=!(!e||!window.document),b=!(!e||!window.navigator),a,j=" moz Moz MOZ webkit Webkit WebKit WEBKIT ms Ms MS o O".split(" ");a=function(a,b,c){var d,e,f,g,h;e=b.indexOf("{}");0<=e?(d=b.slice(0,e),e=b.slice(e+2)):(d="",e=b);b=e.charAt(0).toUpperCase()+e.slice(1);f=0;for(g=j.length;f<g;f++){h=d+j[f]+e;if(h in a)break;h=d+j[f]+b;if(h in a)break}if(f<g)return c?h:a[h]};var m=c&&!!document.evaluate,
n=e&&!!window.JSON,f=e&&!!window.orientation,h=c&&!!document.querySelector,p=!(!a(document,"exitFullscreen")&&!a(document,"cancelFullScreen")),q=e&&!!("ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch),t=b&&!(!navigator.msPointerEnable&&!navigator.pointerEnabled),s=!(!c||!document.implementation||!document.implementation.hasFeature("MutationEvents","2.0"))||e&&window.MutationEvent,r=e&&!!window.addEventListener,v=c&&!(document.documentElement&&document.documentElement.style.filter),
D=c&&!(document.documentElement&&document.documentElement.style.opacity),G=c&&!!a(document.createElement("div").style,"transition",!0),y;y=e&&a(window,"CSSMatrix");y=!!y&&void 0!==(new y).m11;var m={window:e,document:c,navigator:b,xpath:m,json:n,orientation:f,querySelector:h,fullscreen:p,touchEvents:q,pointerEvents:t,mutationEvents:s,eventCapture:r,filterCSS:v,opacityCSS:D,transitionsCSS:G,matrixCSS:y,dragAndDrop:e&&!(window.System&&window.System.Gadget)},n=b&&(navigator.systemLanguage||navigator.language).toLowerCase().split("-"),
f=n[0]||"en",n={lang:f,locale:n[1]||"us",dir:-1!==["ar","he"].indexOf(f)?"rtl":"ltr"},w=/(opera|ie|firefox|chrome|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/,A=/(webkit)[\s\/:]([\w\d\.]+)/,E=/ip(?:ad|od|hone)/,x=/webos|wossystem/,z=/blackberry/,K=/android/,H=/mac|win|linux/;l={Engine:{name:"unknown",version:0},Platform:{name:"unknown"},Features:m,Locale:n,detect:function(){var a,d,e,f=b&&navigator.userAgent.toLowerCase()||"";d=f.match(w)||f.match(A)||(g.process?[null,"nodeJS",
g.process.version]:[null,"unknown",0]);a="ie"===d[1]&&c&&document.documentMode||("opera"===d[1]&&d[4]?d[4]:d[2]);e=parseInt(a,10);d="version"===d[1]?d[3]:d[1];a={name:d,version:e,fullVersion:a};a[d]=e;a[d+e]=!0;a.webkit=!!f.match(/webkit/);l.Engine=a;f=(b&&navigator.platform.toLowerCase()||"").split(" ")[0];e=b&&navigator.userAgent.toLowerCase()||"";f={name:e.match(E)?"ios":e.match(x)?"webos":e.match(z)?"blackberry":(e.match(K)||f.match(H)||g.process?[f]:["other"])[0]};f[f.name]=!0;f.ipad=!!e.match(/ipad/);
f.tablet=f.ipad||!!e.match(/tablet/);l.Platform=f;c&&(document.documentElement.className+=" "+l.Engine.name+" "+l.Engine.name+l.Engine.version+" "+l.Platform.name)},isOnline:function(a,c){void 0!==a&&c?(l.onLine=!!a,setTimeout(function(){delete l.onLine},c)):void 0===l.onLine&&(l.onLine=b&&void 0!==navigator.onLine?!0===navigator.onLine:!0);return l.onLine},getOrientation:e&&window.self===window.top&&window.orientation?function(){return 90===Math.abs(window.orientation)?"landscape":"portrait"}:function(){var a=
l.getSize();return 1>a.width/a.height?"portrait":"landscape"},getSize:function(){var a,b,d=0,f=0;if(e&&"number"===typeof window.innerWidth)d=window.innerWidth,f=window.innerHeight;else if(c)if(a=document.documentElement,b=document.body,a&&(a.clientWidth||a.clientHeight))d=a.clientWidth,f=a.clientHeight;else if(b&&(b.clientWidth||b.clientHeight))d=b.clientWidth,f=b.clientHeight;return{width:d,height:f}},getScrolls:function(){var a=0,b=0;e&&"number"===typeof window.pageYOffset&&(b=window.pageYOffset,
a=window.pageXOffset);return{y:b,x:a}},getScrollbarWidth:k.memoize(function(){var a,b,d=0;c&&(a=document.documentElement,b=document.createElement("div"),b.style.cssText="width:100px;height:100px;overflow:scroll;position:absolute;top:-9999px;",a.appendChild(b),d=b.offsetWidth-b.clientWidth,a.removeChild(b));return d}),addStar:function(a,b){if(e)if(window.sidebar)window.sidebar.addPanel(b,a,"");else if(window.external)window.external.AddFavorite(a,b);else if(window.opera&&window.print)return!0},getVendorProperty:a};
l.detect();return d.namespace("Utils/Client",l,d)});
define("UWA/Ajax",["UWA/Core","UWA/Utils","UWA/Utils/Client"],function(d,k){var l={getRequest:function(g,e){e=d.merge(e||{},{url:g,method:"GET",async:!0,onComplete:function(){},onFailure:function(a){throw a;},onTimeout:function(a){throw a;},onCancel:function(){}});var c,b,a,j,m=e.method||"GET",n=e.headers||{},f=e.authentication,h=l.onStateChange;/OPTIONS|GET|HEAD|POST|PUT|DELETE|TRACE|CONNECT/i.test(m)&&(m=m.toUpperCase());e.data&&("string"!==typeof e.data&&(e.data=k.toQueryString(e.data)),"GET"===
m&&(g+=(-1<g.indexOf("?")?"&":"?")+e.data,e.url=g,delete e.data));e.cors||(n["X-Requested-With"]||(n["X-Requested-With"]="XMLHttpRequest"),n["X-Requested-Method"]||(n["X-Requested-Method"]=m));"POST"===m&&!n["Content-Type"]&&(n["Content-Type"]="application/x-www-form-urlencoded; charset=utf-8");f&&(f.username&&f.password?(j=g.split("://"),g=j[0]+"://"+f.username+":"+f.password+"@"+j[1]):g+=(-1<g.indexOf("?")?"&":"?")+k.toQueryString(f));a=e.cors?l.createCORSRequest():l.createRequest();if(!a)e.onFailure(Error("Unable to initiate XMLHttpRequest object."));
a.cancel=function(){a.aborted=!0;a.abort()};a.open(m,g,e.async);e.timeout&&(c=Error("Request timed out after "+e.timeout+" ms"),d.owns(a,"timeout")&&e.async?(a.timeout=e.timeout,a.ontimeout=e.onTimeout.bind(c)):a.timeoutTimer=setTimeout(function(){a.timedout=!0;a.abort();e.onTimeout(c)},e.timeout));e.cors?(a.onerror=function(){d.merge(a,{readyState:4,status:500});h(a,e)},a.onload=function(){d.merge(a,{readyState:4,status:200});h(a,e)}):a.onreadystatechange=h.bind(l,a,e);if(a.setRequestHeader)for(b in n)n.hasOwnProperty(b)&&
a.setRequestHeader(b,n[b]);return a},createRequest:function(){var d;window.XMLHttpRequest?d=new window.XMLHttpRequest:window.ActiveXObject&&(d=new window.ActiveXObject("Msxml2.XMLHTTP"));return d},createCORSRequest:function(){var d;window.XMLHttpRequest&&(d=new window.XMLHttpRequest,!d.withCredentials&&window.XDomainRequest&&(d=new window.XDomainRequest));return d},request:function(d,e){var c;e=e||{};c=l.getRequest(d,e);c.send(e.data||null);if(!e.async)l.onStateChange(c,e);return c},onStateChange:function(d,
e){if(4===d.readyState)if(d.timeoutTimer&&clearTimeout(d.timeoutTimer),d.status&&400>d.status){e.onComplete(d.responseText,d.responseXML);try{e.cors?(delete d.onerror,delete d.onload):delete d.onreadystatechange}catch(c){}}else if(!d.timedout)if(d.aborted)e.onCancel(d,e);else e.onFailure(Error('NetworkError: url "'+e.url+'" return ResponseCode with value "'+(d.status||0)+"'."))}};return d.namespace("Ajax",l,d)});
define("UWA/Json",["UWA/Core","UWA/Utils","UWA/Utils/Client","UWA/Ajax"],function(d,k,l,g){var e={jsonp:{},encode:JSON.stringify,decode:JSON.parse,isJson:function(c){var b=!1;if(d.is(c,"string"))try{JSON.parse(c),b=!0}catch(a){}return b},xmlToJson:function(c){var b,a,d,g,l=function(){return this.nodeValue},f=function(){return parseInt(this.nodeValue,10)};"string"===typeof c&&(c=k.loadXml(c));if((!c.attributes||0===c.attributes.length)&&c.childNodes&&1===c.childNodes.length&&-1!==c.childNodes[0].nodeName.indexOf("#"))a=
c.childNodes[0].nodeValue;else{a={};if(c.attributes)for(b=0;b<c.attributes.length;b++)d=c.attributes[b],g=d.nodeName,a[g]?(a[g]=k.splat(a[g]),a[g].push(d.nodeValue)):a[g]=d.nodeValue;for(b=0;b<c.childNodes.length;b++)d=c.childNodes[b],g=d.nodeName,a[g]?(a[g]=k.splat(a[g]),a[g].push(e.xmlToJson(d))):-1===g.indexOf("#")?a[g]=e.xmlToJson(d):0<d.nodeValue.trim().length&&(a.nodeValue=d.nodeValue,a.toString=l,a.valueOf=f)}return a},path:function(c,b,a){var e,g=[],k=a&&a.resultType||"VALUE",f=function(a,
b){var d,e=a.replace(/(^|[^\\])@/g,"$1_v").replace(/\\@/g,"@");try{return d=c&&b&&eval(e)}catch(f){throw new SyntaxError("UWA.Json.path: "+f.message+": "+e);}},h=function(a,b,c,e,f){var g,h;h=d.typeOf(c);if("array"===h){g=0;for(h=c.length;g<h;g++)c.hasOwnProperty(g)&&f(g,a,b,c,e)}else if("object"===h)for(g in c)c.hasOwnProperty(g)&&f(g,a,b,c,e)},l=function(a,b,c){if(""!==a){var d,q,G;a=a.split(";");d=a.shift();a=a.join(";");if(b&&b.hasOwnProperty(d))l(a,b[d],c+";"+d);else if("*"===d)h(d,a,b,c,function(a,
b,c,d,e){l(a+";"+c,d,e)});else if(".."===d)l(a,b,c),h(d,a,b,c,function(a,b,c,d,e){"object"===typeof d[a]&&l("..;"+c,d[a],e+";"+a)});else if(/^\(.*?\)$/.test(d))l(f(d,b,c.substr(c.lastIndexOf(";")+1))+";"+a,b,c);else if(/^\?\(.*?\)$/.test(d))h(d,a,b,c,function(a,b,c,d,e){f(b.replace(/^\?\((.*?)\)$/,"$1"),d instanceof Array?d[a]:d,a)&&l(a+";"+c,d,e)});else if(/^(-?[0-9]*):(-?[0-9]*):?([0-9]*)$/.test(d))e(d,a,b,c);else if(/,/.test(d)){d=d.split(/'?,'?/);q=0;for(G=d.length;q<G;q++)l(d[q]+";"+a,b,c)}}else if(c){a=
g.length;if("PATH"===k){d=c.split(";");q="$";b=1;for(c=d.length;b<c;b++)q+=/^[0-9*]+$/.test(d[b])?"["+d[b]+"]":"['"+d[b]+"']";b=q}g[a]=b}};e=function(a,b,c,d){if(c instanceof Array){var e=c.length,f=0,g=1,h=e;a.replace(/^(-?[0-9]*):(-?[0-9]*):?(-?[0-9]*)$/g,function(a,b,c,d){f=parseInt(b||f,10);h=parseInt(c||h,10);g=parseInt(d||g,10)});f=0>f?Math.max(0,f+e):Math.min(e,f);h=0>h?Math.max(0,h+e):Math.min(e,h);for(a=f;a<h;a+=g)l(a+";"+b,c,d)}};if(b&&c&&("VALUE"===k||"PATH"===k)){a=l;var q=[];b=b.replace(/[\['](\??\(.*?\))[\]']|\['(.*?)'\]/g,
function(a,b,c){return"[#"+(q.push(b||c)-1)+"]"}).replace(/'?\.'?|\['?/g,";").replace(/;;;|;;/g,";..;").replace(/;$|'?\]|'$/g,"").replace(/#([0-9]+)/g,function(a,b){return q[b]});a(b.replace(/^\$;?/,""),c,"$");return g.length?g:!1}},request:function(c,b){b=b||{};var a,j,m,n,f,h,p,q,t,s,r,v=k.matchUrl(c,window.location)?!1:d.Data&&d.Data.useJsonpRequest&&!d.Data.allowCrossOriginRequest,D=c,G=l.isOnline,y=e.jsonp,w={fromDataRequest:!1,useOfflineCache:!1,async:!0,timeout:!1,callback:"jsonp"+(Date.now()+
Math.ceil(1E4*Math.random())),callbackName:"callback",callbackMode:"function",callbackModeName:"callbackMode",onCancel:function(){},onFailure:function(a){throw a;},onComplete:function(){}};b=d.merge(b||{},w);b.timeout=!1===b.timeout?b.useOfflineCache?15E3:25E3:parseInt(b.timeout,10);b.data&&(c+=(-1<c.indexOf("?")?"&":"?")+k.toQueryString(b.data));j=b.callback.replace(/[^a-zA-Z0-9_.]/g,"");if(m=b.callbackMode)c=c.replace(/\=(\?|%3F)/g,"="+j),c+=(-1<c.indexOf("?")?"&":"?")+b.callbackName+"="+j,c+="&"+
b.callbackModeName+"="+m;if(2048<c.length)throw Error("Proxified url is more than 2048 characters, you should consider using POST and CORS Ajax.");n=b.onFailure;h=b.onTimeout||n;f=b.onComplete;p=b.useOfflineCache;q=b.fromDataRequest;b.onFailure=function(a,b){e.cleanRequest(j,b);if(p&&!1===q){var c=e.getFromCache(D);d.is(c)?(G()&&G(!1,5E3),f(c)):n(a)}else n(a)};b.onTimeout=function(a,b){e.cleanRequest(j,b);if(p&&!1===q){var c=e.getFromCache(D);d.is(c)?(G()&&G(!1,5E3),f(c)):h(a)}else h(a)};b.onComplete=
function(a){e.cleanRequest(j,b);try{if(q&&a&&a.error&&a.error.type&&"UWA_Platform_Exposition"===a.error.type)throw Error('ObjectError: url "{0}" return Error with value "{1}"'.format(q,a.error.message||a.error));f(a)}catch(c){n(c)}};0>b.cache&&(c+=(-1<c.indexOf("?")?"&":"?")+"_="+Date.now());if(p&&!1===G())b.onFailure(Error("Network is Offline"));else v?(y[j]={readyState:!1,options:b},"object"===m?(t=Date.now(),s=13,r=function(a){var b;b=Date.now();void 0!==window[j]?(y[j].readyState="loaded",a.onComplete(window[j])):
b>t+a.timeout?(b-=t,a.onTimeout(Error("Request timed out after "+b+"ms with timeout value "+a.timeout+" ms"))):y[j].poll=setTimeout(r.bind(this,a),s)}):(window[j]=function(a){void 0!==y[j]&&(y[j].data=a,y[j].readyState="loaded")},t=Date.now(),s=13,r=function(a){var b;b=Date.now();if("loaded"===y[j].readyState)a.onComplete(y[j].data);else b>t+a.timeout?(b-=t,a.onTimeout(Error("Timout request after "+b+"ms with timeout value "+a.timeout+" ms"))):y[j].poll=setTimeout(r.bind(this,a),s)}),a=document.getElementsByTagName("head")[0],
a=d.createElement("script",{type:"text/javascript",src:c,async:b.async}).inject(a),y[j].script=a,r(b),a={jsonId:j,script:a,cancel:function(){y[j].aborted=!0;e.cleanRequest(j)}}):a=g.request(c,d.merge({headers:{Accept:"application/json,text/javascript,*/*","X-Request":"JSON"},onComplete:function(a){var c;m&&!e.isJson(a)&&(c=a.indexOf("("),a=a.substr(c+1,a.lastIndexOf(")")-c-1));if(e.isJson(a))b.onComplete(d.Json.decode(a));else b.onFailure(Error('Invalid JSON Response: "'+a+'"'))},onFailure:b.onFailure},
b));return a},cleanRequest:function(c){var b,a=document.getElementsByTagName("head")[0],d=e.jsonp[c];if(d&&(b=d.options,clearTimeout(d.poll),"object"!==b.callbackMode&&(window[c]=function(){try{delete window[c]}catch(a){}}),d.script&&(a.removeChild(d.script),delete d.script),d.aborted))b.onCancel(null,b)}};return d.namespace("Json",e,d)});
define("UWA/Object",["UWA/Core","UWA/Function"],function(d){var k,l,g,e,c,b,a,j=Function.prototype.call,m=Object.prototype,n=j.bind(m.hasOwnProperty),f=m.toString,h=function(a){var b=typeof a;return("object"===b||"function"===b)&&null!==a};k=Function("return this")();if(a=n(m,"__defineGetter__"))l=j.bind(m.__defineGetter__),g=j.bind(m.__defineSetter__),c=j.bind(m.__lookupGetter__),b=j.bind(m.__lookupSetter__);d.merge(Object,{getPrototypeOf:function(a){return a.__proto__||(a.constructor?a.constructor.prototype:
m)},getOwnPropertyDescriptor:function(d,e){var f,g,j,k;if(!h(d))throw new TypeError("Object.getOwnPropertyDescriptor called on a non-object:"+d);if(n(d,e)){g={enumerable:!0,configurable:!0};if(a&&(f=d.__proto__,d.__proto__=m,j=c(d,e),k=b(d,e),d.__proto__=f,j||k))return j&&(g.get=j),k&&(g.set=k),g;g.value=d[e];return g}},getOwnPropertyNames:function(a){if(!h(a))throw new TypeError("Object.getOwnPropertyNames called on a non-object:"+a);return Object.keys(a)},create:function(a,b){var c;c=function(){};
null===a?c={__proto__:null}:(c.prototype=a,c=new c,c.__proto__=a);void 0!==b&&Object.defineProperties(c,b);return c}});var p=function(a){try{return Object.defineProperty(a,"sentinel",{}),a.hasOwnProperty("sentinel")}catch(b){}},q=(j=Object.defineProperty)&&p({});k=j&&void 0===k.document||p(k.document.createElement("div"));var t=j&&!q||!k&&Object.defineProperty;if(!j||t)Object.defineProperty=function(d,e,f){var j;if(!h(d))throw new TypeError("Object.defineProperty called on non-object: "+d);if(!h(f))throw new TypeError("Property description must be an object: "+
f);if(t)try{return t.call(Object,d,e,f)}catch(k){}if(n(f,"value"))a&&(c(d,e)||b(d,e))?(j=d.__proto__,d.__proto__=m,delete d[e],d[e]=f.value,d.__proto__=j):d[e]=f.value;else{if(!a)throw new TypeError("getters & setters can not be defined on this javascript engine");n(f,"get")&&l(d,e,f.get);n(f,"set")&&g(d,e,f.set)}return d};d.merge(Object,{defineProperties:function(a,b){if(!h(a))throw new TypeError("Object.defineProperties called on a non-object");for(var c in b)n(b,c)&&Object.defineProperty(a,c,b[c]);
return a},seal:function(a){if(!h(a))throw new TypeError("Object.seal called on a non-object");return a},freeze:function(a){if(!h(a))throw new TypeError("Object.freeze called on a non-object");return a},preventExtensions:function(a){if(!h(a))throw new TypeError("Object.preventExtensions called on a non-object");return a},isSealed:function(a){if(!h(a))throw new TypeError("Object.isSealed called on a non-object");return!1},isFrozen:function(a){if(!h(a))throw new TypeError("Object.isFrozen called on a non-object");
return!1},isExtensible:function(a){var b,c;if(!h(a))throw new TypeError("Object.isExtensible called on a non-object");for(c="";n(a,c);)c+="?";a[c]=!0;b=n(a,c);delete a[c];return b},keys:function(a){if(!h(a))throw new TypeError("Object.keys called on a non-object");var b,c,d=[];c=!n({toString:null},"toString");var e="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),f=e.length;for(b in a)n(a,b)&&d.push(b);if(c)for(b=0;b<f;b++)c=e[b],n(a,c)&&d.push(c);
return d},equals:function(a,b){return e(a,b,[],[])}});e=function(a,b,c,g){var h,j,m,k,l;if(a===b)return 0!==a||1/a==1/b;if(null==a||null==b)return a===b;h=f.call(a);if(h!=f.call(b))return!1;switch(h){case "[object String]":return a==String(b);case "[object Number]":return a!=+a?b!=+b:0==a?1/a==1/b:a==+b;case "[object Date]":case "[object Boolean]":return+a==+b;case "[object RegExp]":return a.source==b.source&&a.global==b.global&&a.multiline==b.multiline&&a.ignoreCase==b.ignoreCase}if("object"!=typeof a||
"object"!=typeof b)return!1;for(j=c.length;j--;)if(c[j]==a)return g[j]==b;c.push(a);g.push(b);j=0;m=!0;if("[object Array]"==h){j=a.length;for(m=j==b.length;m&&0<j;)j--,m=e(a[j],b[j],c,g)}else{h=a.constructor;k=b.constructor;if(h!==k&&!("[object Function]"==f.call(h)&&h instanceof h&&"[object Function]"==f.call(k)&&k instanceof k))return!1;for(l in a)if(d.owns(a,l)&&(j++,m=d.owns(b,l)&&e(a[l],b[l],c,g),!m))break;if(m){for(l in b)if(d.owns(b,l)&&!j--)break;m=!j}}c.pop();g.pop();return m};return d.namespace("Object",
Object,d)});
define("UWA/Utils/InterCom","UWA/Core UWA/Utils UWA/Class UWA/Class/Debug UWA/Json UWA/Array UWA/Object".split(" "),function(d,k,l,g,e){var c=new (l.extend(g,{Adapter:{},listeners:[],currentAdapter:null,getAdapter:function(){if(null===this.currentAdapter){var b,a,c=this.Adapter;for(a in c)if(c.hasOwnProperty(a)&&(b=new this.Adapter[a],b.isAvailable())){this.currentAdapter=b;break}this.log("INIT: Adapter "+a)}return this.currentAdapter},removeListener:function(b){var a,c,d=this.listeners;a=0;for(c=
d.length;a<c;a++)b===d[a]&&delete d[a];return this.getAdapter().removeListener(b)},addListener:function(b){this.listeners.unshift(b);return this.getAdapter().addListener(b)},dispatchMessage:function(b,a,c){var d,e;if(a===window){a=this.listeners;e={origin:window.location.toString(),source:window,data:b};b=0;for(c=a.length;b<c&&!(d=a[b](e,e.data));b++);}else d=this.getAdapter().dispatchMessage(b,a,c);return d},encode:function(b){var a=this,c=["string","array","boolean","number"];try{return e.encode(b)}catch(g){return e.encode(b,
function(b,f){if(!d.is(f,c))try{e.encode(f)}catch(g){a.log('Ignored mesage part due invalid type for "'+f+'"'),f=null}return f})}},decode:function(b){return e.decode(b)}}));c.Adapter.PostMessage=function(){return{isAvailable:function(){return window.postMessage},removeListener:function(b){window.addEventListener?window.removeEventListener("message",b,!1):window.attachEvent&&window.detachEvent("onmessage",b)},addListener:function(b){var a;"function"===typeof b&&(a=function(a){try{var d=c.decode(a.data);
b(a,d)}catch(e){c.log("Unable to call listener cause:"+e)}},window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent&&window.attachEvent("onmessage",a));return a},dispatchMessage:function(b,a){var d=!1;b=c.encode(b);if((a=a||(parent.postMessage?parent:parent.document.postMessage?parent.document:void 0))&&a.postMessage)a.postMessage(b,"*"),d=!0;return d}}};c.Adapter.SameDomain=function(){function b(a,b){try{if((!b.source||a!==window.parent||a.name!==b.source)&&a.UWA&&a.UWA.Utils&&
a.UWA.Utils.InterCom){var c=a.UWA.Utils.InterCom.listeners,d,e,g;d=0;for(e=c.length;d<e&&!(g=c[d](b,b.data));d++);return g}}catch(k){return!1}}return{isAvailable:function(){try{return window!==window.parent&&window.parent.document.location.host===document.location.host}catch(a){return!1}},removeListener:function(){},addListener:function(){},dispatchMessage:function(a){var c,d={origin:window.location.toString(),source:window,data:a};if(!b(parent,d)){a=0;for(c=parent.frames.length;a<c&&!(parent.frames[a]!==
window.parent&&b(parent.frames[a],d));a++);}}}};c.Adapter.FrameCallback=function(){function b(){e&&(document.body&&0<d.length)&&document.body.appendChild(d.shift());0<d.length&&setTimeout(b,10)}var a=0,d=[],e=!0;return{isAvailable:function(){return!0},removeListener:function(){},addListener:function(){},dispatchMessage:function(g,f,h){var l;f=window.location.toString();h=k.parseUrl(h);h=h.protocol+"://"+h.domain+"/intercom.html";g=c.encode({origin:k.encodeUrl(f),source:window.name,data:g});g="#"+
+new Date+a++ +"&"+g;l=document.createElement("iframe");l.setAttribute("src",h+g);l.style.position="absolute";l.style.top="-2000px";l.style.left="0px";l.onload=function(){e=!0;l.parentNode.removeChild(l)};d.push(l);setTimeout(b,10);return!0}}};c.Adapter.Anchor=function(){function b(a){return(a.location||a.src).toString().replace(/#.*$/,"")}var a=0;return{isAvailable:function(){return!0},removeListener:function(a){clearInterval(a.interval)},addListener:function(a){var b,d;if("function"===typeof a){d=
this.lastHash=window.location.hash.toString();b=function(){var b,e=window.location.hash.toString(),f=/^#?\d+&/;if(e!==d&&f.test(e)){d=e;try{b=c.decode(e.replace(f,"")),b.source=b.origin=decodeURIComponent(b.origin),a(b,b.data)}catch(g){c.log("Unable to call listener cause:"+g)}}};var e=window,g=void 0!==window.onhashchange;if(!g)try{e.setAttribute("onhashchange","return;"),g="function"===typeof e.onhashchange}catch(k){}g?window.addEventListener?window.addEventListener("hashchange",b,!1):window.attachEvent&&
window.attachEvent("onhashchange",b):a.interval=setInterval(b,10)}return b},dispatchMessage:function(d,e,g){var f=c.encode({origin:k.encodeUrl(b(window)),source:window.nane,data:d});a:{d=e;if("string"===typeof d){var h,l,q=0,t=[window],s;if(document.body){s=document.body.getElementsByTagName("iframe");h=0;for(l=s.length;h<l;h++)t.push(s[h])}h=0;for(l=t.length;h<l;h++)if(s=-1!==navigator.userAgent.indexOf("Firefox")?decodeURIComponent(b(t[h])):b(t[h]),s===d){d=t[h]===window?t[h]:t[h].contentWindow;
break}else q++;if(q===t.length){e=parent;break a}}else d=d||parent;e=d}if(!e||!g)return!1;d=function(){var b="#"+ +new Date+a++ +"&"+f;e.location=g+b};0<a?d():(a++,setTimeout(d,0));return!0}}};c.Server=function(b,a){function e(){var a,b=[];for(a in q)q.hasOwnProperty(a)&&b.push(a);return b}function g(a){var b,c,d,f,h=e();b=0;for(c=h.length;b<c;b++){d=0;for(f=a.length;d<f;d++)if(a[d]===h[b])return!0}return!1}function l(a,b,e,f,g,h){g=r[g];if(f=f[g]||!1)h=d.merge(h||{},{responseName:g,time:Date.now()}),
c.log('SERVER RESPONSE: server "'+b+'" response "'+g+'" using event "'+f+'" on socket "'+e+'"'),a(b,f,h,void 0,e)}function f(a,b,d,g,m,r){var s,t,v,H;m=m?k.splat(m):e();r=r||{};l(f,a,g,r,"before");s=0;for(t=m.length;s<t;s++)v=m[s],H=q[v],v!==g&&(c.log('SERVER DISPATCH: server "'+a+'" dispatch event "'+b+'" to "'+v+'" from "'+(g||a)+'"'),l(f,a,g,r,"loop",{targetSocket:v}),H=c.dispatchMessage({event:b,data:d,target:{sockets:k.splat(v)},origin:{socket:g,server:a}},H.source,H.origin),!1===H&&b!==p&&(c.log('SERVER: server "'+
a+'" disconnected from socket "'+v+'"'),h.unsubscribeSocket(v)));l(f,a,g,r,"after")}var h,p="unSubscribeToServer",q={},t={},s=null,r={before:"beforeDispatch",loop:"onDispatchLoop",after:"afterDispatch"};a=d.merge(a||{},{isPublic:!0});var v=b;c.Server.Instances[v]&&(c.Server.Instances[v].disconnect(),delete c.Server.Instances[v]);b=v||Math.floor(65236*Math.random());h={id:null,isPublic:a.isPublic,dispatchEvent:function(a,c,d,e,g){f(b,a,c,d,e,g);return this},addListener:function(a,b){t[a]=b;return this},
removeListener:function(a){delete t[a];return this},subscribeSocket:function(a,c,d){q[a]={source:c,origin:decodeURIComponent(d)};f(b,"subscribeToServer",{},void 0,a);return this},unsubscribeSocket:function(a){f(b,p,{},void 0,a);delete q[a];return this},disconnect:function(){f(b,p,{},void 0);q={};c.removeListener(s);return this},connect:function(){s=c.addListener(function(a,d){var e;if(d.target.servers&&(0===d.target.sockets.length&&d.target.servers&&-1!==d.target.servers.indexOf(b)||d.target.sockets&&
g(d.target.sockets,h))){if("subscribeToServer"===d.event)c.log('SERVER: server "'+b+'" register new socket "'+d.origin.socket+'"'),h.subscribeSocket(d.origin.socket,a.source,a.origin);else if(d.event===p)c.log('SERVER: server "'+b+'" unregister socket "'+d.origin.socket+'"'),h.unsubscribeSocket(d.origin.socket);else if(g(d.target.sockets,h)||-1!==d.target.servers.indexOf(b)){if(c.log('SERVER PREDISPATCH: server "'+b+'" dispatch event "'+d.event+'" from "'+d.origin.socket+'"'),0===d.target.sockets.length&&
(d.target.sockets=Object.keys(q)),f(b,d.event,d.data,d.origin.socket,d.target.sockets,d.eventResponses),d.event&&t[d.event])t[d.event](d.data,d)}else c.log('SERVER: server "'+b+'" refuse message for event "'+d.event+'"');e=!0}else c.log('SERVER: server "'+b+'" refuse message for event "'+d.event+'"'),e=!1;return e},this)}};h.connect();return c.Server.Instances[b]=h};c.Server.Instances={};c.Socket=function(b,a){function e(){var a,b=[];for(a in h)h.hasOwnProperty(a)&&b.push(a);return b}function g(b,
d,l,n,q,t,w){var A,E,x,z;A=e();n=k.splat(n);q=q&&0<q.length?k.splat(q):A;w=void 0===w?1:w;if(0===A.length&&d!==f)w<a.dispatchRetryLimit?(c.log('SOCKET: socket "'+b+'" delay dispatch event "'+d+'" after '+w+" attempt"),setTimeout(function(){g(b,d,l,n,q,t,w+1)},a.dispatchRetryInterval)):c.log('SOCKET: socket "'+b+'" timeout dispatch event "'+d+'" after '+w+" attempt");else{c.log('SOCKET: socket "'+b+'" will dispatch event "'+d+'"');A=0;for(E=q.length;A<E;A++)x=q[A],z=h[x]||p[x],x&&z&&(c.log('SOCKET: socket "'+
b+'" dispatch event "'+d+'" on "'+x+'"'),c.dispatchMessage({event:d,data:l,target:{servers:[x],sockets:n},origin:{socket:b},eventResponses:t||{}},z.source,z.origin))}d===f&&(w<a.dispatchRetryLimit?setTimeout(function(){0===e().length&&(c.log('SOCKET: socket "'+b+'" retry to connect to server using event "'+d+'" after '+w+" attempt"),g(b,d,l,n,q,t,w+1))},a.dispatchRetryInterval):c.log('SOCKET: socket "'+b+'" fail to connect to server using event "'+d+'" after '+w+" attempt"))}var l,f="subscribeToServer",
h={},p={},q={},t=null;a=d.merge(a||{},{dispatchRetryInterval:250,dispatchRetryLimit:10});b=b||Math.floor(65236*Math.random());l={subscribeServer:function(a,c,d){p[a]={source:c,origin:d};g(b,f,{},[],a);return this},addListener:function(a,b){q[a]=b;return this},dispatchEvent:function(a,c,d,e,f){g(b,a,c,d,e,f);return this},disconnect:function(){h={};c.removeListener(t);return this},connect:function(){t=c.addListener(function(a,d){var e;d.target&&!d.target.servers&&d.target.sockets&&-1!==d.target.sockets.indexOf(b)?
(d.event===f?(h[d.origin.server]={source:a.source,origin:decodeURIComponent(a.origin)},delete p[d.origin.server],c.log('SOCKET: socket "'+b+'" has subcribed from "'+d.origin.server+'"')):"unSubscribeToServer"===d.event?(delete h[d.origin.server],c.log('SOCKET: socket "'+b+'" has unsubcribed from "'+d.origin.server+'"')):d.event&&q[d.event]&&(q[d.event](d.data,d),c.log('SOCKET: socket "'+b+'" call listener for event "'+d.event+'"')),e=!0):(c.log('SOCKET: socket "'+b+'" refuse message for event "'+
d.event+'" with targeted sockets "'+d.target.sockets+'" and servers "'+d.target.servers+'"'),e=!1);return e},this)}};l.connect();return l};return d.namespace("Utils/InterCom",c,d)});
define("UWA/Embedded","UWA/Core UWA/Class UWA/Class/Options UWA/Class/Debug UWA/Class/Events UWA/Utils UWA/Utils/InterCom UWA/String".split(" "),function(d,k,l,g,e,c,b){function a(a,b){for(var c in b)b.hasOwnProperty(c)&&(a.style[c]=b[c])}function j(b,c){var d,e;for(e in c)c.hasOwnProperty(e)&&(d=c[e],"styles"===e?a(b,d):"html"===e?b.innerHTML=d:"text"===e?(b.innerHTML="",b.appendChild(document.createTextNode(d))):b.setAttribute(e,d))}function m(a,b,c){a=document.createElement(a);b&&j(a,b);c&&c.appendChild(a);
return a}var n=k.extend(l,g,e,{url:"",id:null,data:null,version:d.version,elements:null,preferences:null,disableRemote:!0,defaultOptions:{container:null,className:"module",title:null,themeUrl:null,color:"white",height:"auto",width:"100%",maxHeight:!1,bookmarklet:!1,id:null,readOnly:!1,data:{},buildHeader:!1,displayHeader:!0,displayFooter:!0,displayScroller:!1,displayEdit:!0,cache:null,useAsyncFrame:!1,useAppCache:!1,offlineMode:!1,autoLaunch:!0,subDomain:!1,subDomainPattern:"{id}.widget.",remoteName:"uwa.embedded",
exposition:d.hosts.exposition,uwa:d.hosts.uwa},socket:null,init:function(a,b){this.url=a;this.data={};this.elements={};this.preferences=[];this.startTime=(new Date).getTime();this.setOptions(b);b=this.options;var c;c=typeof b.container;"string"===c?this.container=document.getElementById(b.container):"object"===c&&null!==this.options.container?this.container=b.container:(c=document.getElementById("UWA_ASYNC"),this.container=m("div",{id:this.id,"class":b.className}),c?c.parentNode.insertBefore(this.container,
c.nextSibling):(c=document.getElementsByTagName("script"),c=c[c.length-1],c.parentNode.insertBefore(this.container,c)));n.Instances[this.id]=this;if(this.container){if("string"!==typeof this.url)throw Error("UWA.Embedded expect url defined has first param");this.log('Init new instance with container id "'+this.id+'" and widget url "'+this.url+'"');this.render()}else throw Error("UWA.Embedded is unable to get container element with container "+this.container+".");},destroy:function(){},setOptions:function(a){this._parent(a);
a=this.options;a.title&&(a.buildHeader=!0);a.buildHeader&&(a.displayHeader=!1);this.data=a.data||{};if(a.id||!this.id)this.id=a.id||this.generateId();return this},generateId:function(){var a;do a="uwa-"+c.getCheckSum(this.url)+"-"+Math.ceil(1E5*Math.random());while(document.getElementById(a)&&null!==n.Instances[a]);return a},render:function(){var b={},c=this.options,e=this.container,g=navigator.userAgent.toLowerCase().match(/ip(?:ad|od|hone)/);b.wrapper=m("div",{"class":"moduleWrapper"});this.options.buildHeader&&
(b.header=m("div",{"class":"moduleHeader",styles:{position:"relative",overflow:"hidden",height:"23px",padding:"5px 5px 0 5px"}},b.wrapper),b.iconContainer=m("span",{styles:{padding:"0 5px 0 0"}},b.header),b.icon=m("img",{src:c.uwa+d.paths.img+"icon.png","class":"moduleIcon",height:16,width:16,styles:{border:"none",height:16,width:16}},b.iconContainer),b.title=m("span",{text:c.title||"Loading...","class":"moduleTitle",styles:{font:'bold 11px/20px "Lucida Grande",Tahoma,Helvetica,Arial,sans-serif',
verticalAlign:"top"}},b.header));b.body=m("div",{"class":"moduleContent"},b.wrapper);b.iframe=m("iframe",{id:"frame-"+this.id,frameBorder:0,width:"100%",scrolling:c.maxHeight||"auto"!==c.height?"auto":"no"},b.body);a(b.iframe,{display:"block"});c.bookmarklet&&(c.displayScroller=!0,c.height="100%",c.width="320px",a(b.wrapper,{position:"fixed",top:0,right:0,height:c.height,width:c.width,"z-index":99999998}));"auto"!==c.height&&(b.iframe.height=c.height);g&&c.displayScroller&&(b.iframe.scrolling="no");
this.elements=b;e.innerHTML="";e.appendChild(b.wrapper);c.useAsyncFrame?this.renderIframeAsync():this.renderIframe();this.setChromeColor(c.color);this.initRemote()},renderIframe:function(){var a=this.elements.iframe,b=this.getIframeUrl();if(!a.previousIframeUrl||a.previousIframeUrl!==b)a.previousIframeUrl=b,a.src=b},renderIframeAsync:function(){var a;a=JSON.stringify;var b=this.options,c=this.elements.iframe.contentWindow.document,e=b.exposition+"/widget/amd/js?uwaUrl="+this.encodeUrl(this.url),g=
{id:this.id,widgetDomain:window.location.toString().replace(/#.*$/,"")};b.cache&&(e+="&cache="+this.encodeUrl(b.cache));a=["<!DOCTYPE html>","<html>","<head>",'<meta charset="UTF-8" />','<script type="text/javascript">',"   var UWA = {hosts:"+a(d.hosts)+"},",'       curl = {apiName: "require"};',"\x3c/script>",'<script type="text/javascript" src="'+b.uwa+"/lib/curl.js?v="+this.version+'">\x3c/script>','<script type="text/javascript" src="'+e+"&v="+this.version+'">\x3c/script>',"</head>","<body>",
'<script type="text/javascript">','   define("'+this.id+'", ["'+this.url+'"], function (widget) {',"       UWA.extend(widget, "+a(g)+");","   });","\x3c/script>","</body>","</html>"];c.open();c.write(a.join("\n"));c.close()},getIframeUrl:function(){var a,b=[],c=this.options,d=this.data,e={uwaUrl:this.url,id:this.id,cache:c.cache,header:c.displayHeader,footer:c.displayFooter,scroller:c.displayScroller,displayEdit:c.displayEdit,autoLaunch:c.autoLaunch&&!c.offlineMode,useAppCache:c.useAppCache,offlineMode:c.offlineMode,
chromeColor:c.color,widgetDomain:window.location.toString().replace(/#.*$/,""),themeUrl:c.themeUrl};if(!c.offlineMode)for(a in e.readOnly=c.readOnly,d)d.hasOwnProperty(a)&&!e.hasOwnProperty(a)&&(e[a]=d[a]);for(a in e)e.hasOwnProperty(a)&&null!==e[a]&&b.push(a+"="+this.encodeUrl(e[a]));a=this.getIframeDomain()+"?"+b.join("&");if(2048<a.length)throw Error("UWA.Embedded iframe url is more than 2048 characters please implement UWA.Embedded using offlineMode=true.");return a},getIframeDomain:function(){var a,
b=this.options,d=b.exposition;b.subDomain&&(a=c.getCheckSum(this.url),d=d.replace("://","://"+b.subDomainPattern.replace("{id}",a)));return d+"/widget/frame"},initRemote:function(){var a,c=this,d=c.options;c.socket||(n.Servers[d.remoteName]||(n.Servers[d.remoteName]=new b.Server(d.remoteName)),a=new b.Socket(c.id+"-master"),a.subscribeServer(d.remoteName,window,window.location.toString()),a.addListener("widgetMessage",function(a){a=a.args;var b=a.shift();c.disableRemote=b;c.dispatchEvent(b,a);c.disableRemote=
!1}),c.socket=a,c.remoteQueue&&(c.remoteQueue.forEach(function(a){c.sendRemote.apply(c,a)}),c.remoteQueue=null))},sendRemote:function(a){var b,d=c.toArray(arguments);this.socket?(b={id:this.id,args:d},!0===this.disableRemote||this.disableRemote===a?this.log("sendRemote message ignored: "+d):(this.log("sendRemote message: "+d),this.socket.dispatchEvent("environmentMessage",b,[b.id+"-slave"]))):(this.remoteQueue=this.remoteQueue||[],this.remoteQueue.push(d))},launch:function(a,b){void 0!==b&&(this.options.readOnly=
b);void 0!==a&&(this.data=a);this.disableRemote=!1;this.sendRemote("launchWidget",this.data,this.options.readOnly)},setChromeColor:function(a){this.dispatchEvent("onColorize",[a]);this.sendRemote("onColorize",a)},setTitle:function(a){this.dispatchEvent("onUpdateTitle",[a]);this.sendRemote("onUpdateTitle",a)},setIcon:function(a,b){this.dispatchEvent("onUpdateIcon",[a,b]);this.sendRemote("onUpdateIcon",a,b)},setValue:function(a,b){this.dispatchEvent("onUpdateValue",[a,b]);this.sendRemote("onUpdateValue",
a,b)},setValues:function(a){for(var b in a)a.hasOwnProperty(b)&&this.setValue(b,a[b])},resizeHeight:function(a,b){this.dispatchEvent("onResizeHeight",[a,b]);this.sendRemote("onResize")},resizeWidth:function(a,b){this.dispatchEvent("onResizeWidth",[a,b]);this.sendRemote("onResize")},onRegisterWidget:function(){var a=this.options;this.loadTime=(new Date).getTime();this.disableRemote=!1;a.autoLaunch&&(a.offlineMode||a.useAsyncFrame)&&this.launch()},onUpdateTitle:function(a){this.title!==a&&(this.title=
a,this.elements.title&&(this.options.buildHeader&&null===this.options.title)&&j(this.elements.title,{text:a.stripTags()}))},onUpdateIcon:function(a){if(this.icon!==a&&(this.icon=a,this.options.buildHeader)){var b=this.elements.icon,c=m("img",{src:a,onload:function(){b.src=a}});c.complete&&0<c.width&&(b.src=a)}},onUpdatePreferences:function(a){this.preferences=a},onUpdateValue:function(a,b){this.data[a]!==b&&(this.data[a]=b)},onResizeHeight:function(a,b){var c=this.options,d=c.maxHeight;if(this.elements.iframe&&
(b||"auto"===c.height))this.elements.iframe.height=d&&a>d?d:a},onResizeWidth:function(a,b){var c=this.options;if(this.elements.iframe&&(b||"auto"===c.width))this.elements.iframe.width=a},onColorize:function(b){var c=this.options,e=this.elements;c.color=b;c.buildHeader&&("transparent"!==b?a(e.header,{background:'url("'+c.uwa+d.paths.css+"themes/blueberry/img/moduleheader"+("white"!==b?"_"+b:"")+".png?v="+this.version+'") repeat-x scroll center top transparent'}):a(e.header,{background:null}),a(e.title,
{color:"transparent"!==b?"white":"black"}))},getCode:function(a){var b,c,d=this.url,e=JSON.stringify,g=this.options,j={};g.uwa.split("://");var k=["/lib/c/UWA/js/UWA_Embedded.js"];b={uwa:g.uwa,exposition:g.exposition};for(c in g)g.hasOwnProperty(c)&&"container"!==c&&(null!==g[c]&&this.defaultOptions[c]!==g[c])&&(this.isEmpty(g[c])||(j[c]=g[c]));if(a&&1===k.length)a=['<script type="text/javascript">',"var UWA = {hosts:"+e(b)+"}, UWA_ASYNC = UWA_ASYNC || [];",'    UWA_ASYNC.push({url: "'+d+'",options:'+
e(j)+"});","(function () {",'    var a = document.getElementsByTagName("script"), b = a[a.length - 1] || document.body.lastChild,','        c = b.parentNode, d = document.createElement("script"), e = document.createElement("div");','    e.id = "UWA_ASYNC"; d.type = "text/javascript"; d.async = true;','    d.src = ("https:" == document.location.protocol ? "https://" : "http://") + UWA.hosts.uwa.split("://")[1] + "'+k[0]+"?v="+this.version+'";',"    c.insertBefore(d, b); c.insertBefore(e, b)","})();",
"\x3c/script>"];else{a=[];a.push('<script type="text/javascript"> var UWA = {hosts:'+e(b)+"}; \x3c/script>");b=0;for(c=k.length;b<c;b++)a.push('<script type="text/javascript" src="'+g.uwa+k[b]+"?v="+this.version+'">\x3c/script>');a.push('<script type="text/javascript">');a.push('var MyWidget = new UWA.Embedded("'+d+'"'+(!this.isEmpty(j)?","+e(j):"")+");");a.push("\x3c/script>")}return a.join("\n")},encodeUrl:function(a){return"boolean"===typeof a?!1===a?"0":"1":c.encodeUrl(a)},isEmpty:function(a){var b;
if("object"!==typeof a)return!1;for(b in a)if(a.hasOwnProperty(b))return!1;return!0}});n.Instances={};n.Servers={};if(window.UWA_ASYNC){g=window.UWA_ASYNC;d.Widgets=d.Widgets||[];k=0;for(l=g.length;k<l;k++)d.Widgets[k]=new n(g[k].url,g[k].options||{})}return d.namespace("Embedded",n,d)});
